---
  output:
  word_document: default
html_document: default
---

```{r, include=FALSE}

set.seed(126)
library(rjags)
library(mice)
library(tidyr)
library(MCMCvis)
library(dplyr)
options(digits = 2)
rm(list = ls())


library(readxl)

aggregate_data <- read_excel("C:/Users/tdsfrc40/OneDrive - Università degli Studi di Verona/Z/Federico_main/Lavori_Vr/ongoing/lavori_gruppo_CB/NMA/IPD_NMA_RESHIFT/AD_pct_24_07_25.xlsx")
aggregate_data<-do.call(cbind.data.frame, aggregate_data)
setwd("C:/Users/tdsfrc40/OneDrive - Università degli Studi di Verona/Z/Federico_main/Lavori_Vr/ongoing/lavori_gruppo_CB/NMA/IPD_NMA_RESHIFT/an_new_dataset_Jan_26")

load(file="dataset_imputed_21_01_26_pct.RData")

names(merged_imp)[names(merged_imp) == 'clus'] <- 'trialname'
```



```{r names, include=FALSE}
# --- Sezione per la ricreazione del full_dataset (se necessaria) ---

studiesIPD_names <- c("Acarturk2022a", "Chibanda2016", "Chowdhary2016", "Cuijpers2022a_Syria", "Cuijpers2022b_Lebanon", "Jordans2019", "Jordans2021", "Khan2019", "Markkula2019", "Matsuzaka2017","Murphy2020", "NakimuliMpungu2020", "Patel2017", "Purgato2021", "Rahman2016", "Rahman2019", "Sangraula2020", "Tol2020", "Z_Acarturk2024", "Z_Acaturk2022b", "Z_Akhtar2021","Z_Bryant2022", "Z_Burchert2024", "Z_DeGraaff2020", "Z_DeGraaff2023", "Z_Spaaji2022", "Z_UNPUBLISHED_CH_main", "Z_UNPUBLISHED_GE_main", "Z_UNPUBLISHED_GE_pilot", "Z_UNPUBLISHED_SW_main")


```

```{r arms, include=FALSE}
merged_imp$arm <- factor(merged_imp$arm,
                          levels = c(1,2,3,4,5,6,7,8,9,10,11))

```

```{r dataIPD, include=FALSE}
summary(merged_imp$age)
merged_imp$age[merged_imp$age < 16] <- 16
summary(merged_imp$baseline)
merged_imp$baseline[merged_imp$baseline > 100] <- 100

dataIPD <- merged_imp 

dataIPD <- dataIPD %>%

  rename(treatment = arm) %>%

  mutate(treatment = as.numeric(treatment))

dataIPD <- dataIPD %>%

  group_by(trialname) %>%

  arrange(treatment) %>%

  mutate(arm = as.numeric(factor(treatment,

                                 levels = unique(treatment)[order(unique(treatment))]))) %>%

  ungroup()


table(dataIPD$trialname, dataIPD$treatment)

table(dataIPD$trialname, dataIPD$arm)

table(dataIPD$treatment, dataIPD$arm)


components <- c("TAU", "PE", "CR", "ACC", "REL", "PM", "BA", "SSS", "IF")

Nc <- length(components)


y.ipd <- dataIPD$endpoint


Npatients <- nrow(dataIPD)

studiesIPD_unique <- unique(dataIPD$trialname) 

Ns.IPD <- length(studiesIPD_unique)


dataIPD$studlab <- as.numeric(factor(dataIPD$trialname, levels = studiesIPD_unique))

studyIPD <- dataIPD$studlab 


dataIPD$comb <- ""

for (i in 1:Npatients) {

  for (j in which(colnames(dataIPD) == "TAU"):which(colnames(dataIPD) == "IF")) {

    if (dataIPD[i, j] == "1") {

      dataIPD$comb[i] <- paste(dataIPD$comb[i], "+", colnames(dataIPD)[j])

    }

  }

}

dataIPD$comb <- substr(dataIPD$comb, 4, nchar(dataIPD$comb))


armIPD <- dataIPD$arm


unique_arm_combinations <- dataIPD %>%
  group_by(studlab, arm) %>%
  slice(1) %>% 
  ungroup()

for (i in 1:Nc) {
  component_name <- components[i]

  if (is.factor(unique_arm_combinations[[component_name]])) {
    unique_arm_combinations[[component_name]] <- as.numeric(as.character(unique_arm_combinations[[component_name]]))
  }


  temp_data_for_pivot <- unique_arm_combinations[, c("studlab", "arm", component_name)]

  temp_cIPD <- temp_data_for_pivot %>%
    pivot_wider(names_from = arm, values_from = !!sym(component_name), names_prefix = "arm_")

  cols_to_select <- names(temp_cIPD)[startsWith(names(temp_cIPD), "arm_")]
  assign(paste0("cIPD_", i), as.matrix(temp_cIPD[, cols_to_select]))
}

```


```{r check_pre_stand, include=FALSE}
class(dataIPD$baseline)

class(dataIPD$age)

class(dataIPD$gender)

class(dataIPD$edu_bin)

class(dataIPD$stc_bin)

class(dataIPD$empl_bin)
```

```{r mean, include=FALSE}

x <- dataIPD$age
stats <- c(
  Mean = mean(x),
SD = sd(x)
)

format(round(stats, 20), nsmall = 10)

summary(dataIPD$baseline)
#dataIPD$baseline[dataIPD$baseline > 100] <- 100

x <- dataIPD$baseline
stats <- c(
  Mean = mean(x),
SD = sd(x)
)
format(round(stats, 20), nsmall = 10)

stc_bin<-as.numeric(dataIPD$stc_bin)
x <- stc_bin
stats <- c(
  Mean = mean(as.numeric(x)),
SD = sd(x)
)
format(round(stats, 20), nsmall = 10)

empl_bin<-as.numeric(dataIPD$empl_bin)
x <- empl_bin
stats <- c(
  Mean = mean(as.numeric(x)),
SD = sd(x)
)
format(round(stats, 20), nsmall = 10)

edu_bin<-as.numeric(dataIPD$edu_bin)
x <- edu_bin
stats <- c(
  Mean = mean(as.numeric(x)),
SD = sd(x)
)
format(round(stats, 20), nsmall = 10)

gender<-as.numeric(dataIPD$gender)
x <- gender
stats <- c(
  Mean = mean(as.numeric(x)),
SD = sd(x)
)
format(round(stats, 20), nsmall = 10)
```

```{r standardize, include=FALSE}
dataIPD$age <- as.vector(scale(dataIPD$age))

dataIPD$empl_bin <- as.vector(scale(as.numeric(dataIPD$empl_bin)))

dataIPD$stc_bin <- as.vector(scale(as.numeric(dataIPD$stc_bin)))

dataIPD$gender <- as.vector(scale(as.numeric(as.character(dataIPD$gender))))

dataIPD$edu_bin <- as.vector(scale(as.numeric(dataIPD$edu_bin)))
dataIPD <- dataIPD %>%

  group_by(trialname) %>%

  mutate(

    cluster_id_within_study = if (all(is.na(cluster)) | n_distinct(cluster) == 1) {

      as.integer(rep(1, n()))

    } else {

      as.integer(factor(cluster, levels = unique(cluster)))

    },

    n_clusters_within_study = n_distinct(cluster_id_within_study)

  ) %>%

  ungroup()


dataIPD$y <- dataIPD$endpoint 

dataIPD$clusterIPD <- dataIPD$cluster_id_within_study 

```


```{r aggregate, include=FALSE}
dataAD <- as.data.frame(aggregate_data)


dataAD2 <- dataAD %>%

  group_by(id_study) %>%

  mutate(arm_new = rank(arm, ties.method = "first")) %>% 

  filter(arm_new %in% c(1, 2)) %>% 

  ungroup()


dataAD2$y <- dataAD2$post_m_1

dataAD2$n_AD <- dataAD2$post_n_1 

dataAD2$sd_AD <- dataAD2$post_sd_1

dataAD2$study <- dataAD2$trial_name

dataAD2 <- dataAD2[!(is.na(dataAD2$y)),] 

Ns <- length(unique(dataAD2$study)) 

studies_AD_unique <- unique(dataAD2$study) 


dataAD2$comb <- ""

for (j in 1:length(dataAD2$study)) {

  for (i in (which(colnames(dataAD2) == "TAU")):(which(colnames(dataAD2) == "IF"))) {

    if (dataAD2[j, i] == "1") {

      dataAD2$comb[j] <- paste(dataAD2$comb[j], "+", colnames(dataAD2)[i])

    }

  }

}

dataAD2$comb <- substr(dataAD2$comb, 4, nchar(dataAD2$comb))

for (i in 1:Nc) {
  component_name <- components[i]

  if (is.factor(dataAD2[[component_name]])) {
    dataAD2[[component_name]] <- as.numeric(as.character(dataAD2[[component_name]]))
  }

  temp_data_for_pivot_ad <- dataAD2[, c("study", "arm", component_name)] 

  temp_c <- temp_data_for_pivot_ad %>%
    pivot_wider(names_from = arm, values_from = !!sym(component_name), names_prefix = "arm_")


  cols_to_select_ad <- names(temp_c)[startsWith(names(temp_c), "arm_")]
  assign(paste0("c", i), as.matrix(temp_c[, cols_to_select_ad]))
}
```


```{r check_pre_model, include=FALSE}
class(dataIPD$baseline)

class(dataIPD$age)

class(dataIPD$gender)

class(dataIPD$edu_bin)

class(dataIPD$stc_bin)

class(dataIPD$empl_bin)
```

```{r cluster, include=FALSE}
unique_cluster_study_pairs <- dataIPD %>%
  select(studlab, cluster) %>%
  distinct() %>%
  arrange(studlab, cluster) 
unique_cluster_study_pairs$global_cluster_id <- 1:nrow(unique_cluster_study_pairs)

study_for_cluster_data <- unique_cluster_study_pairs %>%
  `[`(, c("global_cluster_id", "studlab")) %>%
  arrange(global_cluster_id)

dataIPD <- dataIPD %>%
  left_join(unique_cluster_study_pairs[, c("studlab", "cluster", "global_cluster_id")], 
            by = c("studlab", "cluster"))

Nclusters_global <- max(dataIPD$global_cluster_id, na.rm = TRUE)

clusterID_jags <- as.vector(dataIPD$global_cluster_id)

N_clusters_per_study_df <- dataIPD %>%
  group_by(studlab) %>%
  summarise(count_clusters = n_distinct(global_cluster_id)) %>%
  ungroup() %>%
  arrange(studlab) 
N_clusters_per_study_IPD_jags <- N_clusters_per_study_df$count_clusters
``` 


```{r model, include=FALSE}
clusters_summary_by_study <- dataIPD %>%
  group_by(studlab) %>%
  summarise(
    total_patients_in_study = n(),
    n_unique_clusters_global = n_distinct(global_cluster_id),
    list_of_global_cluster_ids = paste(sort(unique(global_cluster_id)), collapse = ", "),
  ) %>%
  ungroup() %>%
  arrange(studlab)

print(clusters_summary_by_study)
```

```{r model, include=FALSE}

summary(dataIPD$endpoint)
summary(dataIPD$baseline)
#dataIPD$baseline[dataIPD$baseline > 100] <- 100
#dataIPD$baseline<-dataIPD$baseline-mean(dataIPD$baseline)

```

```{r model, include=FALSE}
model1_con_AD_common_pct <- "
model {
  prec.pat <- 1 / (sigma * sigma)
  sigma ~ dnorm(0, 0.01)I(0,) # Prior for residual standard deviation (IPD)

  for (s in 1:Ns.IPD) { # Ns.IPD è il numero di studi IPD
    for (a in 1:2) { # Assumendo 2 bracci per studio IPD

      phi.IPD[s, a] <- u[s] +
                         d[2] * cIPD_2[s, a] +
                         d[3] * cIPD_3[s, a] +
                         d[4] * cIPD_4[s, a] +
                         d[5] * cIPD_5[s, a] +
                         d[6] * cIPD_6[s, a] +
                         d[7] * cIPD_7[s, a] +
                         d[8] * cIPD_8[s, a] +
                         d[9] * cIPD_9[s, a]
    }
  }

  for (i in 1:Npatients) {
    y.ipd[i] ~ dnorm(muIPD[i], prec.pat)
    muIPD[i] <- phi.IPD[studyIPD[i], arm[i]] + # Effetto base dello studio + effetto delle componenti per il braccio del paziente
    cluster.effect[clusterID[i]] * cluster_indicator[studyIPD[i]] + # Effetto cluster
                  beta.baseline * baseline[i] + # Covariate individuali (effetti principali)
                  beta.age * age[i] +
                  beta.gender * gender[i] +
                  beta.empl_bin * empl_bin[i] +
                  beta.stc_bin * stc_bin[i] +
                  beta.edu_bin * edu_bin[i] +
              
                  ( gamma.base[2] * cIPD_2[studyIPD[i],arm[i]]* baseline[i] +
                   gamma.base[3] * cIPD_3[studyIPD[i],arm[i]]* baseline[i] + gamma.base[4] * cIPD_4[studyIPD[i],arm[i]]* baseline[i] + gamma.base[5] * cIPD_5[studyIPD[i],arm[i]]* baseline[i] + gamma.base[6] * cIPD_6[studyIPD[i],arm[i]]* baseline[i] + gamma.base[7] * cIPD_7[studyIPD[i],arm[i]]* baseline[i] + gamma.base[8] * cIPD_8[studyIPD[i],arm[i]]* baseline[i] + gamma.base[9] * cIPD_9[studyIPD[i],arm[i]]* baseline[i] + gamma.age[2] * cIPD_2[studyIPD[i],arm[i]]* age[i] + gamma.age[3] * cIPD_3[studyIPD[i],arm[i]]* age[i] + gamma.age[4] * cIPD_4[studyIPD[i],arm[i]]* age[i] + gamma.age[5] * cIPD_5[studyIPD[i],arm[i]]* age[i] + gamma.age[6] * cIPD_6[studyIPD[i],arm[i]]* age[i] + gamma.age[7] * cIPD_7[studyIPD[i],arm[i]]* age[i] + gamma.age[8] * cIPD_8[studyIPD[i],arm[i]]* age[i] + gamma.age[9] * cIPD_9[studyIPD[i],arm[i]]* age[i] + gamma.gender[2] * cIPD_2[studyIPD[i],arm[i]]* gender[i] + gamma.gender[3] * cIPD_3[studyIPD[i],arm[i]]* gender[i] + gamma.gender[4] * cIPD_4[studyIPD[i],arm[i]]* gender[i] + gamma.gender[5] * cIPD_5[studyIPD[i],arm[i]]* gender[i] + gamma.gender[6] * cIPD_6[studyIPD[i],arm[i]]* gender[i] + gamma.gender[7] * cIPD_7[studyIPD[i],arm[i]]* gender[i] + gamma.gender[8] * cIPD_8[studyIPD[i],arm[i]]* gender[i] + gamma.gender[9] * cIPD_9[studyIPD[i],arm[i]]* gender[i] +  gamma.empl_bin[2] * cIPD_2[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[3] * cIPD_3[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[4] * cIPD_4[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[5] * cIPD_5[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[6] * cIPD_6[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[7] * cIPD_7[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[8] * cIPD_8[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[9] * cIPD_9[studyIPD[i],arm[i]]* empl_bin[i] + gamma.stc_bin[2] * cIPD_2[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[3] * cIPD_3[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[4] * cIPD_4[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[5] * cIPD_5[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[6] * cIPD_6[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[7] * cIPD_7[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[8] * cIPD_8[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[9] * cIPD_9[studyIPD[i],arm[i]]* stc_bin[i] + gamma.edu_bin[2] * cIPD_2[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[3] * cIPD_3[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[4] * cIPD_4[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[5] * cIPD_5[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[6] * cIPD_6[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[7] * cIPD_7[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[8] * cIPD_8[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[9] * cIPD_9[studyIPD[i],arm[i]]* edu_bin[i] 
                  ) - (
                    gamma.base[2] * cIPD_2[studyIPD[i],1]* baseline[i] + gamma.base[3] * cIPD_3[studyIPD[i],1]* baseline[i] + gamma.base[4] * cIPD_4[studyIPD[i],1]* baseline[i] + gamma.base[5] * cIPD_5[studyIPD[i],1]* baseline[i] + gamma.base[6] * cIPD_6[studyIPD[i],1]* baseline[i] + gamma.base[7] * cIPD_7[studyIPD[i],1]* baseline[i] + gamma.base[8] * cIPD_8[studyIPD[i],1]* baseline[i] + gamma.base[9] * cIPD_9[studyIPD[i],1]* baseline[i] + gamma.age[2] * cIPD_2[studyIPD[i],1]* age[i] + gamma.age[3] * cIPD_3[studyIPD[i],1]* age[i] + gamma.age[4] * cIPD_4[studyIPD[i],1]* age[i] + gamma.age[5] * cIPD_5[studyIPD[i],1]* age[i] + gamma.age[6] * cIPD_6[studyIPD[i],1]* age[i] + gamma.age[7] * cIPD_7[studyIPD[i],1]* age[i] + gamma.age[8] * cIPD_8[studyIPD[i],1]* age[i] + gamma.age[9] * cIPD_9[studyIPD[i],1]* age[i] + gamma.gender[2] * cIPD_2[studyIPD[i],1]* gender[i] + gamma.gender[3] * cIPD_3[studyIPD[i],1]* gender[i] + gamma.gender[4] * cIPD_4[studyIPD[i],1]* gender[i] + gamma.gender[5] * cIPD_5[studyIPD[i],1]* gender[i] + gamma.gender[6] * cIPD_6[studyIPD[i],1]* gender[i] + gamma.gender[7] * cIPD_7[studyIPD[i],1]* gender[i] + gamma.gender[8] * cIPD_8[studyIPD[i],1]* gender[i] + gamma.gender[9] * cIPD_9[studyIPD[i],1]* gender[i] +  gamma.empl_bin[2] * cIPD_2[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[3] * cIPD_3[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[4] * cIPD_4[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[5] * cIPD_5[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[6] * cIPD_6[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[7] * cIPD_7[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[8] * cIPD_8[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[9] * cIPD_9[studyIPD[i],1]* empl_bin[i] + gamma.stc_bin[2] * cIPD_2[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[3] * cIPD_3[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[4] * cIPD_4[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[5] * cIPD_5[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[6] * cIPD_6[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[7] * cIPD_7[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[8] * cIPD_8[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[9] * cIPD_9[studyIPD[i],1]* stc_bin[i] + gamma.edu_bin[2] * cIPD_2[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[3] * cIPD_3[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[4] * cIPD_4[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[5] * cIPD_5[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[6] * cIPD_6[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[7] * cIPD_7[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[8] * cIPD_8[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[9] * cIPD_9[studyIPD[i],1]* edu_bin[i] )
  }

  for (s in 1:Ns.IPD) {
    delta1[s, 1] <- 0 # Braccio di riferimento per lo studio 's'
    # delta1[s,2] è l'effetto di trattamento per il braccio 2 vs braccio 1 dello studio 's'
    delta1[s, 2] ~ dnorm(md1IPD[s, 2], prect)
    md1IPD[s, 2] <- (d[2] * cIPD_2[s,2] + d[3] * cIPD_3[s,2] + d[4] * cIPD_4[s,2] + d[5] * cIPD_5[s,2] + d[6] * cIPD_6[s,2] + d[7] * cIPD_7[s,2] + d[8] * cIPD_8[s,2] + d[9] * cIPD_9[s,2]) -
                    (d[2] * cIPD_2[s,1] + d[3] * cIPD_3[s,1] + d[4] * cIPD_4[s,1] + d[5] * cIPD_5[s,1] + d[6] * cIPD_6[s,1] + d[7] * cIPD_7[s,1] + d[8] * cIPD_8[s,1] + d[9] * cIPD_9[s,1])
  }

  for (s in 1:Ns) {
    for (a in 1:2) { # Assuming fixed 2 arms for AD studies
      y[s, a] ~ dnorm(muAD[s, a], precisionAD[s, a])
      muAD[s, a] <- u[Ns.IPD + s] + deltaAD[s, a] # Use u[Ns.IPD + s] for AD studies' baseline effect
      precisionAD[s, a] <- n[s, a] / (sd[s, a] * sd[s, a])
    }

    deltaAD[s, 1] <- 0
    
deltaAD[s, 2] ~ dnorm(mdAD[s], prec.total.AD)
    mdAD[s] <- (d[2] * c2[s, 2] + d[3] * c3[s, 2] + d[4] * c4[s, 2] +
                d[5] * c5[s, 2] + d[6] * c6[s, 2] + d[7] * c7[s, 2] +
                d[8] * c8[s, 2] + d[9] * c9[s, 2]) -
               (d[2] * c2[s, 1] + d[3] * c3[s, 1] + d[4] * c4[s, 1] +
                d[5] * c5[s, 1] + d[6] * c6[s, 1] + d[7] * c7[s, 1] +
                d[8] * c8[s, 1] + d[9] * c9[s, 1])
  }


  for (idx in 1:(Ns.IPD + Ns)) {
    u[idx] ~ dnorm(0, prec.u)
  }
  tau.u ~ dnorm(0, 0.01)I(0,) # Prior for heterogeneity between studies (std dev)
  prec.u <- 1 / pow(tau.u, 2) # Precision for u

  tau ~ dnorm(0, 0.01)I(0,) # Prior for heterogeneity of treatment effects (std dev)
  tau.sq <- pow(tau, 2)
  prect <- 1 / tau.sq # Precision for treatment effects


  tau.AD.extra ~ dnorm(0, 0.01)I(0,) # Prior per la std dev dell'eterogeneità AD

tau.AD.extra.sq <- pow(tau.AD.extra, 2) # Varianza aggiuntiva per AD
prec.total.AD <- 1 / (tau.sq + tau.AD.extra.sq) # Precisione totale per AD

    tau.cluster.common ~ dnorm(0, 0.01)I(0,)
  prec.cluster.common <- 1 / pow(tau.cluster.common, 2)


 for (j in 1:Nclusters) { # Nclusters è il numero totale di cluster unici nell'IPD
    cluster.effect[j] ~ dnorm(0, prec.cluster.common)
  } 

  d[1] <- 0 

  beta.baseline ~ dnorm(0, 10)
  beta.age ~ dnorm(0, 0.01)
  beta.gender ~ dnorm(0, 0.01)
  beta.empl_bin ~ dnorm(0, 0.01)
  beta.stc_bin ~ dnorm(0, 0.01)
  beta.edu_bin ~ dnorm(0, 0.01)

  for (k in 2:Nc) { # Loop da 3 a Nc, escludendo cIPD_2 (PE)
    d[k] ~ dnorm(0, 0.04)
  }

   lambda_baseline ~ dgamma(50, 9)
  lambda ~ dgamma(2, 15) # Prior for the rate parameter of the double exponential
  
  # Nel blocco dei prior
for (k in 2:8) { # Salta il 9
    gamma.base[k] ~ ddexp(0, lambda_baseline)
    gamma.age[k] ~ ddexp(0, lambda)
    gamma.gender[k] ~ ddexp(0, lambda)
    gamma.empl_bin[k] ~ ddexp(0, lambda)
    gamma.stc_bin[k] ~ ddexp(0, lambda)
    gamma.edu_bin[k] ~ ddexp(0, lambda)
}

# Fissa esplicitamente a zero le interazioni per la componente 9
gamma.base[9] <- 0
gamma.age[9] <- 0
gamma.gender[9] <- 0
gamma.empl_bin[9] <- 0
gamma.stc_bin[9] <- 0
gamma.edu_bin[9] <- 0

for (i in 1:Npatients) {
y.ipd.pred[i] ~ dnorm(muIPD[i], prec.pat)
}

  for (s in 1:Ns) {
    for (a in 1:2) {
      y.AD.pred[s, a] ~ dnorm(muAD[s, a], precisionAD[s, a])
    }
  }
}
"
```

```{r model, include=FALSE}

samps_lambda_con_AD_no_IF_interaz<- list()
N.imputed <- 5
Ns<-4

for (i in 1:N.imputed) {
  print(paste("Dataset", i))
  model1.spec <- textConnection(model1_con_AD_common_pct)

    y.ipd_i <- as.vector(dataIPD$endpoint)
    studyIPD_i <- as.vector(studyIPD)
    arm_i <- as.vector(dataIPD$arm)
  baseline_i <- as.vector(dataIPD$baseline)
    age_i <- as.vector(dataIPD$age) 
    gender_i <- as.vector(dataIPD$gender) 
    empl_bin_i <- as.vector(dataIPD$empl_bin) 
    edu_bin_i <- as.vector(dataIPD$edu_bin) 
    stc_bin_i <- as.vector(dataIPD$stc_bin)
    cIPD_2_i <- as.matrix(get("cIPD_2"))
    cIPD_3_i <- as.matrix(get("cIPD_3"))
    cIPD_4_i <- as.matrix(get("cIPD_4"))
    cIPD_5_i <- as.matrix(get("cIPD_5"))
    cIPD_6_i <- as.matrix(get("cIPD_6"))
    cIPD_7_i <- as.matrix(get("cIPD_7"))
    cIPD_8_i <- as.matrix(get("cIPD_8"))
    cIPD_9_i <- as.matrix(get("cIPD_9"))
    cluster_indicator_jags <- ifelse(N_clusters_per_study_IPD_jags > 1, 1, 0)

    y_i <- matrix(dataAD2$y, nrow = 4, ncol = 2)
    n_AD_i <- matrix(dataAD2$n_AD, nrow = 4, ncol = 2)
    sd_AD_i <- matrix(dataAD2$sd_AD, nrow = 4, ncol = 2)
    cAD_2_i <- as.matrix(get("c2"))
    cAD_3_i <- as.matrix(get("c3"))
    cAD_4_i <- as.matrix(get("c4"))
    cAD_5_i <- as.matrix(get("c5"))
    cAD_6_i <- as.matrix(get("c6"))
    cAD_7_i <- as.matrix(get("c7"))
    cAD_8_i <- as.matrix(get("c8"))
    cAD_9_i <- as.matrix(get("c9"))

  
  data_jags <- list(
    y.ipd = as.vector(dataIPD$endpoint),
  studyIPD = studyIPD_i,
    arm = as.vector(dataIPD$arm),
    clusterID = clusterID_jags, 
  Nclusters = Nclusters_global, 
  cluster_indicator = cluster_indicator_jags,

  cIPD_2 = as.matrix(get("cIPD_2")),
  cIPD_3 = as.matrix(get("cIPD_3")),
  cIPD_4 = as.matrix(get("cIPD_4")),
  cIPD_5 = as.matrix(get("cIPD_5")),
  cIPD_6 = as.matrix(get("cIPD_6")),
  cIPD_7 = as.matrix(get("cIPD_7")),
  cIPD_8 = as.matrix(get("cIPD_8")),
  cIPD_9 = as.matrix(get("cIPD_9")),
    Npatients = Npatients,
    Ns.IPD = Ns.IPD,
  y = y_i,
        n = n_AD_i,
        sd = sd_AD_i,
  c2 = cAD_2_i,
        c3 = cAD_3_i,
        c4 = cAD_4_i,
        c5 = cAD_5_i,
        c6 = cAD_6_i,
        c7 = cAD_7_i,
        c8 = cAD_8_i,
        c9 = cAD_9_i,
  baseline = baseline_i,
        age = age_i,
        gender = gender_i,
        empl_bin = empl_bin_i,
        edu_bin = edu_bin_i,
        stc_bin = stc_bin_i,
  Ns=Ns,
    Nc = Nc
  )

  jags.m <- jags.model(textConnection(model1_con_AD_common_pct), data = data_jags, n.chains = 2, n.adapt = 100)
  params <- c("tau",  "tau.AD.extra", "tau.cluster.common", "d",  "beta.baseline", "gamma.base", "beta.age", "gamma.age",
                "beta.gender", "gamma.gender", "beta.empl_bin", "gamma.empl_bin",
                "beta.stc_bin", "gamma.stc_bin", "beta.edu_bin", "gamma.edu_bin", "y.ipd.pred", "y.AD.pred")
  closeAllConnections()
  samps_lambda_con_AD_no_IF_interaz_temp <- coda.samples(jags.m, params, n.burnin=500, 
                                               n.thin=5, n.iter = 3000)
 
  samps_lambda_con_AD_no_IF_interaz[[i]] <- samps_lambda_con_AD_no_IF_interaz_temp

  saveRDS(samps_lambda_con_AD_no_IF_interaz_temp, file = paste("samps_lambda_con_AD_no_IF_interaz_home", i, ".rds", sep = ""))
}
```

```{r IC, echo=FALSE}
library(coda)

setwd("C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\an_new_dataset_Jan_26\\results_04_02_26")
# 1. Prima carichi i dati come hai già fatto
N.imputed <- 5
samps_lambda_con_AD_no_IF_interaz <- list()


for (i in 1:N.imputed) {
    file_name <- paste("samps_lambda_con_AD_no_IF_interaz", i, ".rds", sep = "")
    if (file.exists(file_name)) {
        samps_lambda_con_AD_no_IF_interaz[[i]] <- readRDS(file_name)
        print(paste("File caricato:", file_name))
    } else {
        print(paste("File non trovato:", file_name))
    }
}

if (length(samps_lambda_con_AD_no_IF_interaz) == 0) {
    stop("Nessun file di campioni caricato. Controlla i nomi dei file.")
}

identical(samps_lambda_con_AD_no_IF_interaz[[1]], samps_lambda_con_AD_no_IF_interaz[[2]])
identical(samps_lambda_con_AD_no_IF_interaz[[1]], samps_lambda_con_AD_no_IF_interaz[[3]])
identical(samps_lambda_con_AD_no_IF_interaz[[1]], samps_lambda_con_AD_no_IF_interaz[[4]])
identical(samps_lambda_con_AD_no_IF_interaz[[1]], samps_lambda_con_AD_no_IF_interaz[[5]])
identical(samps_lambda_con_AD_no_IF_interaz[[2]], samps_lambda_con_AD_no_IF_interaz[[3]])
identical(samps_lambda_con_AD_no_IF_interaz[[2]], samps_lambda_con_AD_no_IF_interaz[[4]])
identical(samps_lambda_con_AD_no_IF_interaz[[2]], samps_lambda_con_AD_no_IF_interaz[[5]])
identical(samps_lambda_con_AD_no_IF_interaz[[3]], samps_lambda_con_AD_no_IF_interaz[[4]])
identical(samps_lambda_con_AD_no_IF_interaz[[3]], samps_lambda_con_AD_no_IF_interaz[[5]])
identical(samps_lambda_con_AD_no_IF_interaz[[4]], samps_lambda_con_AD_no_IF_interaz[[5]])

# MODIFICA QUESTA PARTE DEL TUO CODICE
all_chains_con_AD_lambda <- do.call(rbind, lapply(samps_lambda_con_AD_no_IF_interaz, function(imputation_result) {
    if (inherits(imputation_result, "mcmc.list")) {
        # Per ogni catena MCMC, combina ma FILTRA le colonne
        combined_imputation <- do.call(rbind, lapply(imputation_result, function(chain) {
            chain_matrix <- as.matrix(chain)
            # Seleziona SOLO le colonne che NON sono predizioni
            cols_to_keep <- !grepl("^y\\.(ipd|AD)\\.pred", colnames(chain_matrix))
            chain_matrix[, cols_to_keep, drop = FALSE]
        }))
        combined_imputation
    } else if (inherits(imputation_result, "mcmc")) {
        chain_matrix <- as.matrix(imputation_result)
        cols_to_keep <- !grepl("^y\\.(ipd|AD)\\.pred", colnames(chain_matrix))
        chain_matrix[, cols_to_keep, drop = FALSE]
    } else {
        stop("Formato inatteso per i risultati caricati.")
    }
}))

# Verifica la dimensione
cat("Dimensione di all_chains_con_AD_lambda SENZA predizioni:",
    round(utils::object.size(all_chains_con_AD_lambda)/1024^3, 2), "GB\n")
cat("Numero di parametri mantenuti:", ncol(all_chains_con_AD_lambda), "\n")
cat("Parametri mantenuti (esempi):", 
    paste(colnames(all_chains_con_AD_lambda)[1:min(10, ncol(all_chains_con_AD_lambda))], collapse = ", "), "...\n")
risultati_comb_con_AD <- list()

for (parametro in colnames(all_chains_con_AD_lambda)) {
    campioni <- all_chains_con_AD_lambda[, parametro]
    
    media <- mean(campioni)
    mediana <- median(campioni)
    percentile_2.5 <- quantile(campioni, 0.025)
    percentile_97.5 <- quantile(campioni, 0.975)

    risultati_comb_con_AD[[parametro]] <- data.frame(
        median = mediana,
        mean = media,
        percentile_2.5 = percentile_2.5,
        percentile_97.5 = percentile_97.5,
        stringsAsFactors = FALSE
    )
}

risultati_comb_con_AD_df <- do.call(rbind, risultati_comb_con_AD)

risultati_comb_con_AD_df$median <- round(risultati_comb_con_AD_df$median, 
                                        ifelse(grepl("^u\\[", rownames(risultati_comb_con_AD_df)), 2, 4))
risultati_comb_con_AD_df$mean <- round(risultati_comb_con_AD_df$mean, 
                                      ifelse(grepl("^u\\[", rownames(risultati_comb_con_AD_df)), 2, 4))
risultati_comb_con_AD_df$percentile_2.5 <- round(risultati_comb_con_AD_df$percentile_2.5, 4)
risultati_comb_con_AD_df$percentile_97.5 <- round(risultati_comb_con_AD_df$percentile_97.5, 4)

# Applichiamo l'arrotondamento condizionale (2 per u[...], 4 per gli altri)
# Ma lo facciamo creando delle stringhe formattate

format_val <- function(val, par_name) {
  digits <- if(grepl("^u\\[", par_name)) 2 else 4
  # sprintf crea una stringa con numero fisso di decimali (es. "0.5000")
  sprintf(paste0("%.", digits, "f"), val)
}

# Creiamo un nuovo dataframe per la visualizzazione
risultati_finali_print <- risultati_comb_con_AD_df

for(i in 1:nrow(risultati_finali_print)) {
  p_name <- rownames(risultati_finali_print)[i]
  
  risultati_finali_print$median[i] <- format_val(risultati_comb_con_AD_df$median[i], p_name)
  risultati_finali_print$mean[i]   <- format_val(risultati_comb_con_AD_df$mean[i], p_name)
  risultati_finali_print$percentile_2.5[i]  <- format_val(risultati_comb_con_AD_df$percentile_2.5[i], p_name)
  risultati_finali_print$percentile_97.5[i] <- format_val(risultati_comb_con_AD_df$percentile_97.5[i], p_name)
}

print(risultati_finali_print)
```


```{r per FP normale, include=FALSE}
library(tidyverse)
library(metafor)
library(bayesplot)
library(dplyr)
library(ggplot2)
library(HDInterval)
# 1. Filtra solo i parametri 'd' (componenti principali) dal dataframe dei risultati
component_results <- risultati_comb_con_AD_df %>%
  tibble::rownames_to_column("parameter") %>%
  filter(grepl("^d\\[", parameter)) %>%
  # Escludi d[1] se presente
  filter(parameter != "d[1]")

# 2. Aggiungi i nomi delle componenti (assicurati che l'ordine corrisponda)
component_results$component <- components[-1] # Escludi la prima componente

# 3. Ordina per stima puntuale (opzionale)
component_results <- component_results %>%
  arrange(median)

# 4. Crea il forest plot
forest_plot_from_results <- ggplot(component_results, 
       aes(y = factor(component, levels = rev(component)), 
           x = median, 
           xmin = percentile_2.5, 
           xmax = percentile_97.5)) +
  geom_point(size = 3) +
  geom_errorbar(width = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  scale_x_continuous(breaks = seq(-20, 12, by = 4),  # Sequence from -10 to +12 by 2
                     limits = c(-30, +30)) +          # Set axis limits
  xlab("Effect Estimate (outcome on the 0-100 scale)") +
  ylab("Component") +
  ggtitle("Forest Plot of Component Effects") +
  theme_bw()

print(forest_plot_from_results)
```

```{r exclude d1, include=FALSE}
library(coda)

# Filter parameters (excluding d[1]) for each imputation
samples_for_diag <- lapply(samps_lambda_con_AD_no_IF_interaz, function(imp) {
  # For each imputation chain, remove d[1]
  filtered_chains <- lapply(imp, function(chain) {
    chain[, !grepl("^d\\[1\\]", colnames(chain)), drop = FALSE]
  })
  as.mcmc.list(filtered_chains)  # Keep the mcmc.list structure
})

# Combine all imputation chains in a single mcmc.list
combined_chains <- as.mcmc.list(do.call(c, samples_for_diag))
```

```{r chain_combine, include=FALSE}

# --- NUOVO BLOCCO PER COMBINARE IN UN UNICO mcmc.list ---
# Let’s collect the individual chains from all imputations

all_individual_chains <- unlist(
  lapply(samples_for_diag, function(x) {
    if(inherits(x, "mcmc.list")) as.list(x) else list(x)
  }),
  recursive = FALSE
)
samples_for_diag <- coda::mcmc.list(all_individual_chains)
# --- Now we can use the diagnostic---
param_names <- colnames(samples_for_diag[[1]]) # Take the names from one of the chains

# Exclusion of 'd[1]'
params_to_exclude <- c("d[1]", 
                       grep("^y\\.ipd\\.pred", param_names, value = TRUE))
# Filter the samples to exclude non-estimated parameters

samples_for_gelman <- window(samples_for_diag[, !param_names %in% params_to_exclude], thin = 10)
# Execution of gelman.diag on filtered samples
gelman.diag(samples_for_gelman)
```

```{r ESS, echo=FALSE}
# Calcolo dell'ESS per tutti i parametri filtrati
ess_values <- coda::effectiveSize(samples_for_gelman)

# Visualizza i risultati in modo ordinato
print(sort(ess_values))

# Calcolo del rapporto ESS / Dimensione totale del campione
# (utile per vedere quanto il thinning o l'autocorrelazione pesano)
total_samples <- nrow(samples_for_gelman[[1]]) * length(samples_for_gelman)
ess_efficiency <- ess_values / total_samples
print(sort(ess_efficiency))
```

```{r descaling, echo=FALSE}
# 1. Calcolo SD (Età fissa, altre da merged_imp)
sd_age    <- sd(as.numeric(merged_imp$age), na.rm = TRUE)
sd_gender <- sd(as.numeric(merged_imp$gender), na.rm = TRUE)
sd_empl   <- sd(as.numeric(merged_imp$empl_bin), na.rm = TRUE)
sd_stc    <- sd(as.numeric(merged_imp$stc_bin), na.rm = TRUE)
sd_edu    <- sd(as.numeric(merged_imp$edu_bin), na.rm = TRUE)

sd_map <- c(
  "beta.age"      = sd_age,
  "beta.gender"   = sd_gender,
  "beta.empl_bin" = sd_empl,
  "beta.stc_bin"  = sd_stc,
  "beta.edu_bin"  = sd_edu,
  "beta.baseline" = 1
)

# 2. Ciclo di calcolo con formattazione forzata a 4 decimali
risultati_descaled_list <- list()
beta_params <- c("beta.baseline", "beta.age", "beta.gender", "beta.empl_bin", "beta.stc_bin", "beta.edu_bin")

for (parametro in beta_params) {
    # Campioni originali
    campioni_std <- all_chains_con_AD_lambda[, parametro]
    
    # De-scaling
    campioni_unstd <- campioni_std / sd_map[parametro]
    
    # Calcolo statistiche
    stats <- c(
      median = median(campioni_unstd),
      mean   = mean(campioni_unstd),
      p2.5   = quantile(campioni_unstd, 0.025),
      p97.5  = quantile(campioni_unstd, 0.975)
    )
    
    # Formattazione forzata a stringa con 4 decimali (così vedi 0.1200 e non 0.12)
    risultati_descaled_list[[parametro]] <- data.frame(
        median          = sprintf("%.4f", stats["median"]),
        mean            = sprintf("%.4f", stats["mean"]),
        percentile_2.5  = sprintf("%.4f", stats["p2.5.2.5%"]),
        percentile_97.5 = sprintf("%.4f", stats["p97.5.97.5%"]),
        stringsAsFactors = FALSE
    )
}

# 3. Risultato finale
risultati_descaled_df <- do.call(rbind, risultati_descaled_list)
rownames(risultati_descaled_df) <- c(
  "beta.baseline", "beta.age", "beta.gender", 
  "beta.empl_bin", "beta.stc_bin", "beta.edu_bin"
)

print(risultati_descaled_df)
```




```{r unscaled, include=FALSE}
# 1. Calcolo delle SD (usando il merged_imp aggiornato con i tuoi 'cap' a 16 e 100)
sd_baseline_orig <- sd(merged_imp$baseline, na.rm = TRUE)
sd_PE_orig  <- sd(merged_imp$PE, na.rm = TRUE)
sd_CR_orig  <- sd(merged_imp$CR, na.rm = TRUE)
sd_ACC_orig <- sd(merged_imp$ACC, na.rm = TRUE)
sd_REL_orig <- sd(merged_imp$REL, na.rm = TRUE)
sd_PM_orig  <- sd(merged_imp$PM, na.rm = TRUE)
sd_BA_orig  <- sd(merged_imp$BA, na.rm = TRUE)
sd_SSS_orig <- sd(merged_imp$SSS, na.rm = TRUE)
sd_IF_orig  <- sd(merged_imp$IF, na.rm = TRUE)

# 2. Estrazione campioni
# Nota: Assicurati che i nomi corrispondano a quelli in all_chains_con_AD_lambda
list_samples <- list(
  "Baseline Score" = all_chains_con_AD_lambda[, "beta.baseline"],
  "PE"  = all_chains_con_AD_lambda[, "d[2]"],
  "CR"  = all_chains_con_AD_lambda[, "d[3]"],
  "ACC" = all_chains_con_AD_lambda[, "d[4]"],
  "REL" = all_chains_con_AD_lambda[, "d[5]"],
  "PM"  = all_chains_con_AD_lambda[, "d[6]"],
  "BA"  = all_chains_con_AD_lambda[, "d[7]"],
  "SSS" = all_chains_con_AD_lambda[, "d[8]"],
  "IF"  = all_chains_con_AD_lambda[, "d[9]"]
)

list_sds <- list(
  sd_baseline_orig, sd_PE_orig, sd_CR_orig, sd_ACC_orig, 
  sd_REL_orig, sd_PM_orig, sd_BA_orig, sd_SSS_orig, sd_IF_orig
)

# 3. Creazione del data frame (QUESTO RISOLVE L'ERRORE)
results_df_scaled <- data.frame(
  Predictor = names(list_samples),
  Interpretation = "Change in outcome for a 1-SD increase",
  stringsAsFactors = FALSE
)

# 4. Funzione di riepilogo a 4 decimali
summarize_mcmc_fixed <- function(samples) {
  mean_val <- mean(samples)
  ci <- quantile(samples, probs = c(0.025, 0.975))
  sprintf("%.4f (%.4f, %.4f)", mean_val, ci[1], ci[2])
}

# 5. Calcolo e Scaling contemporaneo
results_column <- c()
for (i in 1:length(list_samples)) {
  # Scaling: Moltiplichiamo i campioni originali per la loro SD
  scaled_samples <- list_samples[[i]] * list_sds[[i]]
  results_column[i] <- summarize_mcmc_fixed(scaled_samples)
}

# Aggiunta della colonna al data frame
results_df_scaled$`Mean (95% Credibility Interval)` <- results_column

# 6. Stampa
print(knitr::kable(results_df_scaled, align = c('l', 'l', 'c'), 
                   caption = "Standardized Component Effects (Z-scores)"))
```

```{r interaz, include=FALSE}
library(dplyr)
library(knitr)

# Mappa delle covariate e delle SD (assicurati che sd_age, sd_gender_orig, ecc. siano definiti)
covariate_map <- list(
  baseline   = "base",       
  age        = "age",
  gender     = "gender",
  empl_bin   = "empl_bin",
  stc_bin    = "stc_bin",
  edu_bin    = "edu_bin"
)

sd_list <- list(
  baseline = NA, 
  age      = sd_age,
  gender   = sd_gender,
  empl_bin = sd_empl,
  stc_bin  = sd_stc,
  edu_bin  = sd_edu
)

# Funzione per estrarre le colonne gamma
extract_gamma_samples <- function(mat, var_pattern) {
  gamma_cols <- grep(paste0("^gamma\\.", var_pattern, "(\\[|$)"), colnames(mat), value = TRUE)
  if (length(gamma_cols) == 0) return(NULL)
  return(mat[, gamma_cols, drop = FALSE])
}

results_gamma_cont_df <- data.frame(
  Interaction = character(),
  Component = character(),
  `Coefficient (95% Credibility Interval)` = character(),
  stringsAsFactors = FALSE
)

for (cov_real in names(covariate_map)) {
  cov_model <- covariate_map[[cov_real]]
  gamma_mat <- extract_gamma_samples(all_chains_con_AD_lambda, cov_model)
  if (is.null(gamma_mat)) next
  
  for (colname in colnames(gamma_mat)) {
    gamma_samples <- as.numeric(gamma_mat[, colname])
    
    # De-scaling
    if (is.na(sd_list[[cov_real]])) {
      gamma_descaled <- gamma_samples   
    } else {
      gamma_descaled <- gamma_samples / sd_list[[cov_real]]
    }
    
    # Calcolo statistiche
    mean_val <- mean(gamma_descaled, na.rm = TRUE)
    ci <- quantile(gamma_descaled, probs = c(0.025, 0.975), na.rm = TRUE)
    
    # Estrazione nome componente (es. d[2] -> 2)
    component_name <- sub(".*\\[(.*)\\]", "\\1", colname)
    if (component_name == colname) component_name <- "(global)"
    
    # FORMATTAZIONE A 4 DECIMALIE (sprintf forza la visualizzazione degli zeri)
    results_gamma_cont_df[nrow(results_gamma_cont_df) + 1, ] <- c(
      paste(cov_real, "× component", sep = " "),
      component_name,
      sprintf("%.4f (%.4f, %.4f)", mean_val, ci[1], ci[2])
    )
  }
}

# Ordinamento
results_gamma_cont_df <- results_gamma_cont_df %>% arrange(Interaction, Component)

# Stampa Tabella
cat("Tabella dei coefficienti di interazione de-scalati (OUTCOME CONTINUO):\n")
print(knitr::kable(
  results_gamma_cont_df,
  caption = "Interazioni Covariata × Componente (de-scalate a 4 decimali)",
  align = c('l', 'l', 'c')
))
```

```{r maxitab, echo=FALSE}
library(dplyr)
library(knitr)

# --- PRE-REQUISITO: Calcolo SD Originali (Assicurati che questi siano i dati NON scalati) ---
# Se merged_imp è già scalato, usa i valori salvati precedentemente
sd_baseline_orig <- sd(merged_imp$baseline, na.rm = TRUE)
sd_age           <- sd(merged_imp$age, na.rm = TRUE)
sd_gender        <- sd(as.numeric(as.character(merged_imp$gender)), na.rm = TRUE)
sd_empl          <- sd(as.numeric(merged_imp$empl_bin), na.rm = TRUE)
sd_stc           <- sd(as.numeric(merged_imp$stc_bin), na.rm = TRUE)
sd_edu           <- sd(as.numeric(merged_imp$edu_bin), na.rm = TRUE)

# SD per le componenti (binarie)
sd_map_comps <- c(
  "d[2]" = sd(as.numeric(dataIPD$PE), na.rm = TRUE),
  "d[3]" = sd(as.numeric(dataIPD$CR), na.rm = TRUE),
  "d[4]" = sd(as.numeric(dataIPD$ACC), na.rm = TRUE),
  "d[5]" = sd(as.numeric(dataIPD$REL), na.rm = TRUE),
  "d[6]" = sd(as.numeric(dataIPD$PM), na.rm = TRUE),
  "d[7]" = sd(as.numeric(dataIPD$BA), na.rm = TRUE),
  "d[8]" = sd(as.numeric(dataIPD$SSS), na.rm = TRUE),
  "d[9]" = sd(as.numeric(dataIPD$IF), na.rm = TRUE)
)

# --- 2. COSTRUZIONE TABELLA 2 (STANDARDIZED - Z-SCORES DEI PREDITTORI) ---

list_samples_std <- list()

# A. Trasformiamo in Z-score i parametri NON scalati nel modello (Baseline e Componenti)
list_samples_std[["Baseline Score"]] <- all_chains_con_AD_lambda[, "beta.baseline"] * sd_baseline_orig
for(d_name in names(sd_map_comps)) {
  label <- gsub("d\\[|\\d\\]", "", d_name) # Etichetta pulita (es. PE, CR...)
  list_samples_std[[d_name]] <- all_chains_con_AD_lambda[, d_name] * sd_map_comps[d_name]
}

# B. Covariate già standardizzate (age, gender, etc.) -> Restano tali
altre_covs <- c("beta.age", "beta.gender", "beta.empl_bin", "beta.stc_bin", "beta.edu_bin")
for(cov in altre_covs) {
  if(cov %in% colnames(all_chains_con_AD_lambda)) list_samples_std[[cov]] <- all_chains_con_AD_lambda[, cov]
}

# C. Interazioni gamma
gamma_cols <- grep("^gamma\\.", colnames(all_chains_con_AD_lambda), value = TRUE)
for(g in gamma_cols) {
  if(grepl("base", g)) {
    # gamma.base va moltiplicato per SD baseline per diventare Z-score
    list_samples_std[[g]] <- all_chains_con_AD_lambda[, g] * sd_baseline_orig
  } else {
    # Le altre gamma (age, gender...) sono già Z-score rispetto alla covariata
    list_samples_std[[g]] <- all_chains_con_AD_lambda[, g]
  }
}

# --- 3. COSTRUZIONE TABELLA 1 (UNSTANDARDIZED - CLINICA) ---

list_samples_unstd <- list()

# A. Baseline e Componenti (Già scala originale nel modello)
list_samples_unstd[["Baseline Score"]] <- all_chains_con_AD_lambda[, "beta.baseline"]
for(d_name in names(sd_map_comps)) {
  list_samples_unstd[[d_name]] <- all_chains_con_AD_lambda[, d_name]
}

# B. De-scaling covariate e interazioni
sd_map_covs <- c("beta.age"=sd_age, "beta.gender"=sd_gender, "beta.empl_bin"=sd_empl, 
                 "beta.stc_bin"=sd_stc, "beta.edu_bin"=sd_edu)

for(cov in names(sd_map_covs)) {
  if(cov %in% colnames(all_chains_con_AD_lambda)) {
    list_samples_unstd[[cov]] <- all_chains_con_AD_lambda[, cov] / sd_map_covs[cov]
  }
}

for(g in gamma_cols) {
  if(grepl("base", g)) {
    # gamma.base è già clinica (punti test / punti baseline)
    list_samples_unstd[[g]] <- all_chains_con_AD_lambda[, g]
  } else {
    # De-scaling per le altre (es. gamma.age / sd_age)
    for(s_name in names(sd_map_covs)) {
      root <- gsub("beta\\.", "", s_name)
      if(grepl(root, g)) {
        list_samples_unstd[[g]] <- all_chains_con_AD_lambda[, g] / sd_map_covs[s_name]
      }
    }
  }
}

# --- 4. FUNZIONE E STAMPA ---
summarize_mcmc_v2 <- function(samples) {
  med <- median(samples, na.rm = TRUE)
  mn  <- mean(samples, na.rm = TRUE)
  ci  <- quantile(samples, probs = c(0.025, 0.975), na.rm = TRUE)
  sprintf("%.4f (%.4f) [%.4f, %.4f]", med, mn, ci[1], ci[2])
}

tabella_1_unstd <- data.frame(Parameter = names(list_samples_unstd),
                              `Estimate (unstd) [95% CrI]` = sapply(list_samples_unstd, summarize_mcmc_v2),
                              check.names = FALSE)

tabella_2_std <- data.frame(Parameter = names(list_samples_std),
                            `Z-score (std) [95% CrI]` = sapply(list_samples_std, summarize_mcmc_v2),
                            check.names = FALSE)

cat("\n### TABELLA 1: CLINICA\n")
print(kable(tabella_1_unstd))
cat("\n### TABELLA 2: Z-SCORES\n")
print(kable(tabella_2_std))
```

```{r var_keep, echo=FALSE}
vars_keep <- c(
  "baseline",
  "age",
  "gender",
  "stc_bin",
  "edu_bin",
  "empl_bin",
  "y"
)

vars_cont <- c(
  "baseline",
  "age"
)

vars_bin <- c(
  "gender",
  "stc_bin",
  "edu_bin",
  "empl_bin"
)

M<-5

imputed_data <- lapply(1:M, function(m) {
  subset(merged_imp, imputation == m, select = vars_keep)
})
```

```{r cont, echo=FALSE}
make_continuous_model <- function(varname) {
  paste0('
model {

  for (i in 1:N) {
    ', varname, '[i] ~ dnorm(mu[i], tau)
    mu[i] <- alpha + beta * outcome_obs[i]

    ', varname, '_rep[i] ~ dnorm(mu[i], tau)
  }

  alpha ~ dnorm(0, 0.001)
  beta  ~ dnorm(0, 0.001)

  tau <- 1 / (sigma * sigma)
  sigma ~ dunif(0, 10)
}
')
}
```

```{r bin, echo=FALSE}
make_binary_model <- function(varname) {
  paste0('
model {

  for (i in 1:N) {
    ', varname, '[i] ~ dbern(p[i])
    logit(p[i]) <- alpha + beta * outcome_obs[i]

    ', varname, '_rep[i] ~ dbern(p[i])
  }

  alpha ~ dnorm(0, 0.001)
  beta  ~ dnorm(0, 0.001)
}
')
}
```

```{r ppc, echo=FALSE}
ppc_continuous <- function(y_obs, y_rep_matrix) {
  lower <- apply(y_rep_matrix, 2, quantile, 0.05)
  upper <- apply(y_rep_matrix, 2, quantile, 0.95)

  coverage_90 <- mean(y_obs >= lower & y_obs <= upper)
  interval_width <- mean(upper - lower)
  rmse <- sqrt(mean((colMeans(y_rep_matrix) - y_obs)^2))
  rmse_std <- rmse / sd(y_obs)

  list(
    coverage_90 = coverage_90,
    interval_width = interval_width,
    rmse_std = rmse_std
  )
}

ppc_binary <- function(y_obs, y_rep_matrix) {
  p_obs <- mean(y_obs)
  p_rep <- mean(colMeans(y_rep_matrix))
  brier <- mean((colMeans(y_rep_matrix) - y_obs)^2)
  misclass <- mean((colMeans(y_rep_matrix) > 0.5) != y_obs)

  list(
    prop_obs = p_obs,
    prop_rep = p_rep,
    brier = brier,
    misclass = misclass
  )
}
```








```{r prediction, echo=FALSE}
model_string <- "
model {

  for (i in 1:N) {
    baseline[i] ~ dnorm(mu_b[i], tau_b)
    mu_b[i] <- alpha_b + beta_b * outcome_obs[i]

    baseline_rep[i] ~ dnorm(mu_b[i], tau_b)
  }

  alpha_b ~ dnorm(0, 0.001)
  beta_b  ~ dnorm(0, 0.001)

  tau_b <- 1 / (sigma_b * sigma_b)
  sigma_b ~ dunif(0, 10)

  mean_base     <- mean(baseline[])
  mean_base_rep <- mean(baseline_rep[])

  sd_base     <- sd(baseline[])
  sd_base_rep <- sd(baseline_rep[])
}
"
```




```{r JAGS, echo=FALSE}
data_list <- list(
  N = nrow(merged_imp),
  baseline = merged_imp$baseline,
  outcome_obs = merged_imp$y
)
```

```{r JAGS, echo=FALSE}
library(rjags)

jm <- jags.model(
  textConnection(model_string),
  data = data_list,
  n.chains = 3
)

```
