---
  output:
  word_document: default
html_document: default
---

```{r, include=FALSE}
set.seed(126)
library(rjags)
library(mice)
library(tidyr)
library(MCMCvis)
library(dplyr)
options(digits = 2)
rm(list = ls())

library(readxl)

aggregate_data <- read_excel("C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\aggregate_data_only_ok.xlsx")

setwd("C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\an_new_dataset_Jan_26")
load(file="dataset_imputed_21_01_26_std.RData")
View(merged_imp)
```


```{r names, include=FALSE}

names(merged_imp)[names(merged_imp) == 'clus'] <- 'trialname'

studiesIPD_names <- c("Acarturk2022a", "Chibanda2016", "Chowdhary2016", "Cuijpers2022a_Syria", "Cuijpers2022b_Lebanon", "Jordans2019", "Jordans2021", "Khan2019", "Markkula2019", "Matsuzaka2017","Murphy2020", "NakimuliMpungu2020", "Patel2017", "Purgato2021", "Rahman2016", "Rahman2019", "Sangraula2020", "Tol2020", "Z_Acarturk2024", "Z_Acaturk2022b", "Z_Akhtar2021","Z_Bryant2022", "Z_Burchert2024", "Z_DeGraaff2020", "Z_DeGraaff2023", "Z_Spaaji2022", "Z_UNPUBLISHED_CH_main", "Z_UNPUBLISHED_GE_main", "Z_UNPUBLISHED_GE_pilot", "Z_UNPUBLISHED_SW_main")

```

```{r dataIPD, include=FALSE}
summary(merged_imp$age)
merged_imp$arm <- factor(merged_imp$arm,
                          levels = c(1,2,3,4,5,6,7,8,9,10,11))

merged_imp$age[merged_imp$age < 16] <- 16
dataIPD <- merged_imp 
merged_imp$baseline[merged_imp$baseline > 100] <- 100
merged_imp$baseline[merged_imp$baseline < 0] <- 0

dataIPD <- dataIPD %>%

  rename(treatment = arm) %>%

  mutate(treatment = as.numeric(treatment))


dataIPD <- dataIPD %>%

  group_by(trialname) %>%

  arrange(treatment) %>%

  mutate(arm = as.numeric(factor(treatment,

                                 levels = unique(treatment)[order(unique(treatment))]))) %>%

  ungroup()


table(dataIPD$trialname, dataIPD$treatment)

table(dataIPD$trialname, dataIPD$arm)

table(dataIPD$treatment, dataIPD$arm)


components <- c("TAU", "PE", "CR", "ACC", "REL", "PM", "BA", "SSS", "IF")

Nc <- length(components)


y.ipd <- dataIPD$endpoint 


Npatients <- nrow(dataIPD)

studiesIPD_unique <- unique(dataIPD$trialname) 

Ns.IPD <- length(studiesIPD_unique)

dataIPD$studlab <- as.numeric(factor(dataIPD$trialname, levels = studiesIPD_unique))

studyIPD <- dataIPD$studlab 

dataIPD$comb <- ""

for (i in 1:Npatients) {

  for (j in which(colnames(dataIPD) == "TAU"):which(colnames(dataIPD) == "IF")) {

    if (dataIPD[i, j] == "1") {

      dataIPD$comb[i] <- paste(dataIPD$comb[i], "+", colnames(dataIPD)[j])

    }

  }

}

dataIPD$comb <- substr(dataIPD$comb, 4, nchar(dataIPD$comb))


armIPD <- dataIPD$arm


unique_arm_combinations <- dataIPD %>%
  group_by(studlab, arm) %>%
  slice(1) %>%
  ungroup()

for (i in 1:Nc) {
  component_name <- components[i]

  if (is.factor(unique_arm_combinations[[component_name]])) {
    unique_arm_combinations[[component_name]] <- as.numeric(as.character(unique_arm_combinations[[component_name]]))
  }


  temp_data_for_pivot <- unique_arm_combinations[, c("studlab", "arm", component_name)]

  temp_cIPD <- temp_data_for_pivot %>%
    pivot_wider(names_from = arm, values_from = !!sym(component_name), names_prefix = "arm_")

  cols_to_select <- names(temp_cIPD)[startsWith(names(temp_cIPD), "arm_")]
  assign(paste0("cIPD_", i), as.matrix(temp_cIPD[, cols_to_select]))
}

```


```{r check_pre_stand, include=FALSE}
class(dataIPD$baseline)

class(dataIPD$age)

class(dataIPD$gender)

class(dataIPD$edu_bin)

class(dataIPD$stc_bin)

class(dataIPD$empl_bin)

```


```{r standardize, include=FALSE}
dataIPD$age <- as.vector(scale(dataIPD$age))

dataIPD$empl_bin <- as.vector(scale(as.numeric(dataIPD$empl_bin)))

dataIPD$stc_bin <- as.vector(scale(as.numeric(dataIPD$stc_bin)))

dataIPD$gender <- as.vector(scale(as.numeric(as.character(dataIPD$gender))))

dataIPD$edu_bin <- as.vector(scale(as.numeric(dataIPD$edu_bin)))
```


```{r cluster, include=FALSE}
dataIPD <- dataIPD %>%

  group_by(trialname) %>%

  mutate(

    cluster_id_within_study = if (all(is.na(cluster)) | n_distinct(cluster) == 1) {

      as.integer(rep(1, n()))

    } else {

      as.integer(factor(cluster, levels = unique(cluster)))

    },

    n_clusters_within_study = n_distinct(cluster_id_within_study)

  ) %>%

  ungroup()


dataIPD$y <- dataIPD$endpoint

dataIPD$clusterIPD <- dataIPD$cluster_id_within_study 
```


```{r aggregate, include=FALSE}
df <- data.frame(id_study = aggregate_data$id_study, arm = aggregate_data$arm, post_m_1 = aggregate_data$post_m_1, post_sd_1 = aggregate_data$post_sd_1, post_n_1 = aggregate_data$post_n_1)


df_sd_pooled <- df %>%

  group_by(id_study) %>%

summarise(

    sd_pooled = sqrt(

      sum((post_n_1 - 1) * post_sd_1^2, na.rm = TRUE) / (sum(post_n_1, na.rm = TRUE) - 2) 

    )

  )


df_full <- df %>%

  left_join(df_sd_pooled, by = "id_study") %>%

  mutate(

    post_m_1_std = post_m_1 / sd_pooled,  

    post_sd_1_std = post_sd_1 / sd_pooled 

  )

drops <- c("post_m_1", "post_sd_1", "post_n_1")

df_final <- df_full[, !(names(df_full) %in% drops)]

aggregate_data_full <- merge(aggregate_data, df_final, by = c("id_study", "arm"), all.x = TRUE)


dataAD <- as.data.frame(aggregate_data_full)


dataAD2 <- dataAD %>%

  group_by(id_study) %>%

  mutate(arm_new = rank(arm, ties.method = "first")) %>% 
  
  filter(arm_new %in% c(1, 2)) %>%
  ungroup()


dataAD2$y <- dataAD2$post_m_1_std 

dataAD2$n_AD <- dataAD2$post_n_1

dataAD2$sd_AD <- dataAD2$post_sd_1_std 

dataAD2$study <- dataAD2$trial_name


dataAD2 <- dataAD2[!(is.na(dataAD2$y)),]


Ns <- length(unique(dataAD2$study)) 

 Nc <- length(components)


studies_AD_unique <- unique(dataAD2$study)


na <- c()

for (i in 1:Ns) {

  j <- length(dataAD2$arm[dataAD2$study == studies_AD_unique[i]])

  na <- c(na, j)

}


dataAD2$comb <- ""

for (j in 1:length(dataAD2$study)) {

  for (i in (which(colnames(dataAD2) == "TAU")):(which(colnames(dataAD2) == "IF"))) {

    if (dataAD2[j, i] == "1") {

      dataAD2$comb[j] <- paste(dataAD2$comb[j], "+", colnames(dataAD2)[i])

    }

  }

}

dataAD2$comb <- substr(dataAD2$comb, 4, nchar(dataAD2$comb))


for (i in 1:Nc) {
  component_name <- components[i]

  if (is.factor(dataAD2[[component_name]])) {
    dataAD2[[component_name]] <- as.numeric(as.character(dataAD2[[component_name]]))
  }


  temp_data_for_pivot_ad <- dataAD2[, c("study", "arm", component_name)] 

  temp_c <- temp_data_for_pivot_ad %>%
    pivot_wider(names_from = arm, values_from = !!sym(component_name), names_prefix = "arm_")

  cols_to_select_ad <- names(temp_c)[startsWith(names(temp_c), "arm_")]
  assign(paste0("c", i), as.matrix(temp_c[, cols_to_select_ad]))
}
```


```{r check_pre_model, include=FALSE}
class(dataIPD$baseline)

class(dataIPD$age)

class(dataIPD$gender)

class(dataIPD$edu_bin)

class(dataIPD$stc_bin)

class(dataIPD$empl_bin)
```

```{r cluster, include=FALSE}
library(dplyr)
unique_cluster_study_pairs <- dataIPD %>%
  dplyr::select(studlab, cluster) %>%
  distinct() %>%
  arrange(studlab, cluster) 

unique_cluster_study_pairs$global_cluster_id <- 1:nrow(unique_cluster_study_pairs)

study_for_cluster_data <- unique_cluster_study_pairs %>%
  `[`(, c("global_cluster_id", "studlab")) %>%
  arrange(global_cluster_id)


dataIPD <- dataIPD %>%
  left_join(unique_cluster_study_pairs[, c("studlab", "cluster", "global_cluster_id")], # Usa la selezione base qui
            by = c("studlab", "cluster"))

Nclusters_global <- max(dataIPD$global_cluster_id, na.rm = TRUE)

clusterID_jags <- as.vector(dataIPD$global_cluster_id)

N_clusters_per_study_df <- dataIPD %>%
  group_by(studlab) %>%
  summarise(count_clusters = n_distinct(global_cluster_id)) %>%
  ungroup() %>%
  arrange(studlab) 
N_clusters_per_study_IPD_jags <- N_clusters_per_study_df$count_clusters
``` 


```{r model, include=FALSE}
clusters_summary_by_study <- dataIPD %>%
  group_by(studlab) %>%
  summarise(
    total_patients_in_study = n(),
    n_unique_clusters_global = n_distinct(global_cluster_id),
    list_of_global_cluster_ids = paste(sort(unique(global_cluster_id)), collapse = ", "),
  ) %>%
  ungroup() %>%
  arrange(studlab)

print(clusters_summary_by_study)
```

```{r model, include=FALSE}
summary(dataIPD$endpoint)
summary(dataIPD$baseline)
```

```{r model, include=FALSE}
model1_common_std <- "
model {
  prec.pat <- 1 / (sigma * sigma)
  sigma ~ dnorm(0, 0.1)I(0,) # Prior for residual standard deviation (IPD)

  for (s in 1:Ns.IPD) { 
    for (a in 1:2) { 
      phi.IPD[s, a] <- u[s] +
                         d[2] * cIPD_2[s, a] +
                         d[3] * cIPD_3[s, a] +
                         d[4] * cIPD_4[s, a] +
                         d[5] * cIPD_5[s, a] +
                         d[6] * cIPD_6[s, a] +
                         d[7] * cIPD_7[s, a] +
                         d[8] * cIPD_8[s, a] +
                         d[9] * cIPD_9[s, a]
    }
  }

  for (i in 1:Npatients) {
    y.ipd[i] ~ dnorm(muIPD[i], prec.pat)
    muIPD[i] <- phi.IPD[studyIPD[i], arm[i]] + # Effetto base dello studio + effetto delle componenti per il braccio del paziente
    cluster.effect[clusterID[i]] * cluster_indicator[studyIPD[i]] + # Effetto cluster
                  beta.baseline * baseline[i] + # Covariate individuali (effetti principali)
                  beta.age * age[i] +
                  beta.gender * gender[i] +
                  beta.empl_bin * empl_bin[i] +
                  beta.stc_bin * stc_bin[i] +
        beta.edu_bin * edu_bin[i] +

                  (gamma.base[2] * cIPD_2[studyIPD[i],arm[i]]* baseline[i] +
                   gamma.base[3] * cIPD_3[studyIPD[i],arm[i]]* baseline[i] + gamma.base[4] * cIPD_4[studyIPD[i],arm[i]]* baseline[i] + gamma.base[5] * cIPD_5[studyIPD[i],arm[i]]* baseline[i] + gamma.base[6] * cIPD_6[studyIPD[i],arm[i]]* baseline[i] + gamma.base[7] * cIPD_7[studyIPD[i],arm[i]]* baseline[i] + gamma.base[8] * cIPD_8[studyIPD[i],arm[i]]* baseline[i] + gamma.base[9] * cIPD_9[studyIPD[i],arm[i]]* baseline[i] + gamma.age[2] * cIPD_2[studyIPD[i],arm[i]]* age[i] +                   gamma.age[3] * cIPD_3[studyIPD[i],arm[i]]* age[i] + gamma.age[4] * cIPD_4[studyIPD[i],arm[i]]* age[i] + gamma.age[5] * cIPD_5[studyIPD[i],arm[i]]* age[i] + gamma.age[6] * cIPD_6[studyIPD[i],arm[i]]* age[i] + gamma.age[7] * cIPD_7[studyIPD[i],arm[i]]* age[i] + gamma.age[8] * cIPD_8[studyIPD[i],arm[i]]* age[i] + gamma.age[9] * cIPD_9[studyIPD[i],arm[i]]* age[i] + gamma.gender[2] * cIPD_2[studyIPD[i],arm[i]]* gender[i] +
                   gamma.gender[3] * cIPD_3[studyIPD[i],arm[i]]* gender[i] + gamma.gender[4] * cIPD_4[studyIPD[i],arm[i]]* gender[i] + gamma.gender[5] * cIPD_5[studyIPD[i],arm[i]]* gender[i] + gamma.gender[6] * cIPD_6[studyIPD[i],arm[i]]* gender[i] + gamma.gender[7] * cIPD_7[studyIPD[i],arm[i]]* gender[i] + gamma.gender[8] * cIPD_8[studyIPD[i],arm[i]]* gender[i] + gamma.gender[9] * cIPD_9[studyIPD[i],arm[i]]* gender[i] + gamma.empl_bin[2] * cIPD_2[studyIPD[i],arm[i]]* empl_bin[i] +
                   gamma.empl_bin[3] * cIPD_3[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[4] * cIPD_4[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[5] * cIPD_5[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[6] * cIPD_6[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[7] * cIPD_7[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[8] * cIPD_8[studyIPD[i],arm[i]]* empl_bin[i] + gamma.empl_bin[9] * cIPD_9[studyIPD[i],arm[i]]* empl_bin[i] + gamma.stc_bin[2] * cIPD_2[studyIPD[i],arm[i]]* stc_bin[i] +                   gamma.stc_bin[3] * cIPD_3[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[4] * cIPD_4[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[5] * cIPD_5[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[6] * cIPD_6[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[7] * cIPD_7[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[8] * cIPD_8[studyIPD[i],arm[i]]* stc_bin[i] + gamma.stc_bin[9] * cIPD_9[studyIPD[i],arm[i]]* stc_bin[i] +  gamma.edu_bin[2] * cIPD_2[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[3] * cIPD_3[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[4] * cIPD_4[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[5] * cIPD_5[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[6] * cIPD_6[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[7] * cIPD_7[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[8] * cIPD_8[studyIPD[i],arm[i]]* edu_bin[i] + gamma.edu_bin[9] * cIPD_9[studyIPD[i],arm[i]]* edu_bin[i] ) - 
                   # Termini di interazione per il braccio di riferimento (braccio 1 dello studio corrente)
      ( gamma.base[2] * cIPD_2[studyIPD[i],1]* baseline[i] +
                   gamma.base[3] * cIPD_3[studyIPD[i],1]* baseline[i] + gamma.base[4] * cIPD_4[studyIPD[i],1]* baseline[i] + gamma.base[5] * cIPD_5[studyIPD[i],1]* baseline[i] + gamma.base[6] * cIPD_6[studyIPD[i],1]* baseline[i] + gamma.base[7] * cIPD_7[studyIPD[i],1]* baseline[i] + gamma.base[8] * cIPD_8[studyIPD[i],1]* baseline[i] + gamma.base[9] * cIPD_9[studyIPD[i],1]* baseline[i] + gamma.age[2] * cIPD_2[studyIPD[i],1]* age[i] +               gamma.age[3] * cIPD_3[studyIPD[i],1]* age[i] + gamma.age[4] * cIPD_4[studyIPD[i],1]* age[i] + gamma.age[5] * cIPD_5[studyIPD[i],1]* age[i] + gamma.age[6] * cIPD_6[studyIPD[i],1]* age[i] + gamma.age[7] * cIPD_7[studyIPD[i],1]* age[i] + gamma.age[8] * cIPD_8[studyIPD[i],1]* age[i] + gamma.age[9] * cIPD_9[studyIPD[i],1]* age[i] + gamma.gender[2] * cIPD_2[studyIPD[i],1]* gender[i] + 
                   gamma.gender[3] * cIPD_3[studyIPD[i],1]* gender[i] + gamma.gender[4] * cIPD_4[studyIPD[i],1]* gender[i] + gamma.gender[5] * cIPD_5[studyIPD[i],1]* gender[i] + gamma.gender[6] * cIPD_6[studyIPD[i],1]* gender[i] + gamma.gender[7] * cIPD_7[studyIPD[i],1]* gender[i] + gamma.gender[8] * cIPD_8[studyIPD[i],1]* gender[i] + gamma.gender[9] * cIPD_9[studyIPD[i],1]* gender[i] + gamma.empl_bin[2] * cIPD_2[studyIPD[i],1]* empl_bin[i] +                   gamma.empl_bin[3] * cIPD_3[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[4] * cIPD_4[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[5] * cIPD_5[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[6] * cIPD_6[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[7] * cIPD_7[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[8] * cIPD_8[studyIPD[i],1]* empl_bin[i] + gamma.empl_bin[9] * cIPD_9[studyIPD[i],1]* empl_bin[i] + gamma.stc_bin[2] * cIPD_2[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[3] * cIPD_3[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[4] * cIPD_4[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[5] * cIPD_5[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[6] * cIPD_6[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[7] * cIPD_7[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[8] * cIPD_8[studyIPD[i],1]* stc_bin[i] + gamma.stc_bin[9] * cIPD_9[studyIPD[i],1]* stc_bin[i] + gamma.edu_bin[2] * cIPD_2[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[3] * cIPD_3[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[4] * cIPD_4[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[5] * cIPD_5[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[6] * cIPD_6[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[7] * cIPD_7[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[8] * cIPD_8[studyIPD[i],1]* edu_bin[i] + gamma.edu_bin[9] * cIPD_9[studyIPD[i],1]* edu_bin[i]
                  )
  }

  for (s in 1:Ns.IPD) {
    delta1[s, 1] <- 0 # Braccio di riferimento per lo studio 's'
    # delta1[s,2] è l'effetto di trattamento per il braccio 2 vs braccio 1 dello studio 's'
    delta1[s, 2] ~ dnorm(md1IPD[s, 2], prect)
    md1IPD[s, 2] <- (d[2] * cIPD_2[s,2] + d[3] * cIPD_3[s,2] + d[4] * cIPD_4[s,2] + d[5] * cIPD_5[s,2] + d[6] * cIPD_6[s,2] + d[7] * cIPD_7[s,2] + d[8] * cIPD_8[s,2] + d[9] * cIPD_9[s,2]) -
                    (d[2] * cIPD_2[s,1] + d[3] * cIPD_3[s,1] + d[4] * cIPD_4[s,1] + d[5] * cIPD_5[s,1] + d[6] * cIPD_6[s,1] + d[7] * cIPD_7[s,1] + d[8] * cIPD_8[s,1] + d[9] * cIPD_9[s,1])
  }

  for (s in 1:Ns) {
    for (a in 1:2) { # Assuming fixed 2 arms for AD studies
      y[s, a] ~ dnorm(muAD[s, a], precisionAD[s, a])
      muAD[s, a] <- u[Ns.IPD + s] + deltaAD[s, a] # Use u[Ns.IPD + s] for AD studies' baseline effect
      precisionAD[s, a] <- n[s, a] / (sd[s, a] * sd[s, a])
    }

    deltaAD[s, 1] <- 0
    
deltaAD[s, 2] ~ dnorm(mdAD[s], prec.total.AD)
    mdAD[s] <- (d[2] * c2[s, 2] + d[3] * c3[s, 2] + d[4] * c4[s, 2] +
                d[5] * c5[s, 2] + d[6] * c6[s, 2] + d[7] * c7[s, 2] +
                d[8] * c8[s, 2] + d[9] * c9[s, 2]) -
               (d[2] * c2[s, 1] + d[3] * c3[s, 1] + d[4] * c4[s, 1] +
                d[5] * c5[s, 1] + d[6] * c6[s, 1] + d[7] * c7[s, 1] +
                d[8] * c8[s, 1] + d[9] * c9[s, 1])
  }


  for (idx in 1:(Ns.IPD + Ns)) {
    u[idx] ~ dnorm(0, prec.u)
  }
  tau.u ~ dnorm(0, 0.1)I(0,)
  prec.u <- 1 / pow(tau.u, 2) 

  tau ~ dnorm(0, 0.1)I(0,)
  tau.sq <- pow(tau, 2)
  prect <- 1 / tau.sq 

  tau.AD.extra ~ dnorm(0, 0.1)I(0,)
 
tau.AD.extra.sq <- pow(tau.AD.extra, 2)
prec.total.AD <- 1 / (tau.sq + tau.AD.extra.sq)

    tau.cluster.common ~ dnorm(0, 0.1)I(0,)
  prec.cluster.common <- 1 / pow(tau.cluster.common, 2)


 for (j in 1:Nclusters) { 
    cluster.effect[j] ~ dnorm(0, prec.cluster.common)
  } 

  d[1] <- 0

  beta.baseline ~ dnorm(0, 10)
  beta.age ~ dnorm(0, 1)
  beta.gender ~ dnorm(0, 1)
  beta.empl_bin ~ dnorm(0, 1)
  beta.stc_bin ~ dnorm(0, 1)
  beta.edu_bin ~ dnorm(0, 1)

  for (k in 2:Nc) { # Loop da 2 a Nc
    d[k] ~ dnorm (0, 4)
  }
lambda_baseline ~ dgamma(50, 9)
  
  lambda ~ dgamma(1, 0.1) # Prior for the rate parameter of the double exponential
  


  
  for (k in 2:8) { # 
    gamma.base[k] ~ ddexp(0, lambda_baseline)
    gamma.age[k] ~ ddexp(0, lambda)
    gamma.gender[k] ~ ddexp(0, lambda)
    gamma.empl_bin[k] ~ ddexp(0, lambda)
    gamma.stc_bin[k] ~ ddexp(0, lambda)
    gamma.edu_bin[k] ~ ddexp(0, lambda)
  }
  # Forziamo a zero la componente 9 (IF) perché presente in un solo braccio/studio
  # Questo risolve l'instabilità di d[9] e i problemi di convergenza
  gamma.base[9]     <- 0
  gamma.age[9]      <- 0
  gamma.gender[9]   <- 0
  gamma.empl_bin[9] <- 0
  gamma.stc_bin[9]  <- 0
  gamma.edu_bin[9]  <- 0
}
"
``` 




```{r, echo=FALSE}
  samps_lambda_std_no_IF_interaz <- list()
N.imputed <- 5
Ns <- 4

for (i in 1:N.imputed) {

  message("Dataset ", i)

  # --- dati ---
  y.ipd_i   <- as.vector(dataIPD$endpoint)
  studyIPD_i <- as.vector(studyIPD)
  arm_i     <- as.vector(dataIPD$arm)
  baseline_i <- as.vector(dataIPD$baseline)
  age_i     <- as.vector(dataIPD$age)
  gender_i  <- as.vector(dataIPD$gender)
  empl_bin_i <- as.vector(dataIPD$empl_bin)
  edu_bin_i <- as.vector(dataIPD$edu_bin)
  stc_bin_i <- as.vector(dataIPD$stc_bin)

  cluster_indicator_jags <- ifelse(N_clusters_per_study_IPD_jags > 1, 1, 0)

  y_i    <- matrix(dataAD2$y, nrow = 4, ncol = 2)
  n_AD_i <- matrix(dataAD2$n_AD, nrow = 4, ncol = 2)
  sd_AD_i <- matrix(dataAD2$sd_AD, nrow = 4, ncol = 2)

  data_jags <- list(
    y.ipd = y.ipd_i,
    studyIPD = studyIPD_i,
    arm = arm_i,
    clusterID = clusterID_jags,
    Nclusters = Nclusters_global,
    cluster_indicator = cluster_indicator_jags,

    cIPD_2 = cIPD_2, cIPD_3 = cIPD_3, cIPD_4 = cIPD_4,
    cIPD_5 = cIPD_5, cIPD_6 = cIPD_6, cIPD_7 = cIPD_7,
    cIPD_8 = cIPD_8, cIPD_9 = cIPD_9,

    Npatients = Npatients,
    Ns.IPD = Ns.IPD,

    y = y_i, n = n_AD_i, sd = sd_AD_i,
    c2 = c2, c3 = c3, c4 = c4, c5 = c5,
    c6 = c6, c7 = c7, c8 = c8, c9 = c9,

    baseline = baseline_i,
    age = age_i,
    gender = gender_i,
    empl_bin = empl_bin_i,
    edu_bin = edu_bin_i,
    stc_bin = stc_bin_i,

    Ns = Ns,
    Nc = Nc
  )

  jags.m <- jags.model(
    textConnection(model1_common_std),
    data = data_jags,
    n.chains = 2,
    n.adapt = 100
  )

  params <- c(
    "tau","tau.AD.extra","tau.cluster.common",
    "d","beta.baseline","gamma.base",
    "beta.age","gamma.age",
    "beta.gender","gamma.gender",
    "beta.empl_bin","gamma.empl_bin",
    "beta.stc_bin","gamma.stc_bin",
    "beta.edu_bin","gamma.edu_bin"
  )
  
  
  samps_temp <- coda.samples(jags.m, params, n.burnin = 0, n.iter = 3000)

# 2) Burn-in e thinning manuale

  samps_lambda_std_no_IF_interaz_temp <- apply_burnin_thinning(list(samps_temp),
                                                                burn_in = 500, thin_step = 5)[[1]]
 
  samps_lambda_std_no_IF_interaz[[i]] <- samps_lambda_std_no_IF_interaz_temp

  saveRDS(samps_lambda_std_no_IF_interaz_temp, file = paste("samps_lambda_std_no_Chibanda_interaz_home", i, ".rds", sep = ""))

}

```

```{r IC_scaled, echo=FALSE}
library(coda)
library(dplyr)

# --- Impostazioni ---
setwd("C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\an_new_dataset_Jan_26\\results_04_02_26")

N.imputed <- 5

# --- 1. Carica direttamente tutti i campioni in memoria ---
samps_lambda_std_no_IF_interaz <- vector("list", N.imputed)

for (i in 1:N.imputed) {
  file_name <- paste0("samps_lambda_std_no_IF_interaz_home", i, ".rds")
  if (file.exists(file_name)) {
    samps_lambda_std_no_IF_interaz[[i]] <- readRDS(file_name)
    cat("File caricato:", file_name, "\n")
  } else {
    stop("File non trovato:", file_name)
  }
}

# --- 2. Combina le catene e filtra colonne predittive ---
all_chains_std_lambda <- do.call(rbind, lapply(samps_lambda_std_no_IF_interaz, function(imputation_result) {
  if (inherits(imputation_result, "mcmc.list")) {
    # Combina le catene per l’imputazione
    do.call(rbind, lapply(imputation_result, function(chain) {
      chain_matrix <- as.matrix(chain)
    }))
  } else if (inherits(imputation_result, "mcmc")) {
    chain_matrix <- as.matrix(imputation_result)
  } else {
    stop("Formato inatteso per i risultati caricati.")
  }
}))

cat("Dimensione di all_chains_std_lambda SENZA predizioni:",
    round(object.size(all_chains_std_lambda)/1024^3, 2), "GB\n")
cat("Numero di parametri mantenuti:", ncol(all_chains_std_lambda), "\n")
cat("Esempi di parametri:", paste(colnames(all_chains_std_lambda)[1:min(10,ncol(all_chains_std_lambda))], collapse = ", "), "...\n")

# --- 3. Calcolo dei riassunti per ciascun parametro ---
risultati_comb_std <- lapply(colnames(all_chains_std_lambda), function(parametro) {
  campioni <- all_chains_std_lambda[, parametro]
  data.frame(
    median = median(campioni),
    mean = mean(campioni),
    percentile_2.5 = quantile(campioni, 0.025),
    percentile_97.5 = quantile(campioni, 0.975),
    stringsAsFactors = FALSE
  )
})
names(risultati_comb_std) <- colnames(all_chains_std_lambda)
risultati_comb_std_df <- do.call(rbind, risultati_comb_std)

# --- 4. Arrotondamento condizionale ---
risultati_comb_std_df$median <- round(risultati_comb_std_df$median, 
                                      ifelse(grepl("^u\\[", rownames(risultati_comb_std_df)), 2, 4))
risultati_comb_std_df$mean <- round(risultati_comb_std_df$mean, 
                                    ifelse(grepl("^u\\[", rownames(risultati_comb_std_df)), 2, 4))
risultati_comb_std_df$percentile_2.5 <- round(risultati_comb_std_df$percentile_2.5, 4)
risultati_comb_std_df$percentile_97.5 <- round(risultati_comb_std_df$percentile_97.5, 4)

# --- 5. Formattazione come stringhe per stampa ---
format_val <- function(val, par_name) {
  digits <- if(grepl("^u\\[", par_name)) 2 else 4
  sprintf(paste0("%.", digits, "f"), val)
}

risultati_finali_print <- risultati_comb_std_df
for (i in 1:nrow(risultati_finali_print)) {
  p_name <- rownames(risultati_finali_print)[i]
  risultati_finali_print$median[i] <- format_val(risultati_comb_std_df$median[i], p_name)
  risultati_finali_print$mean[i] <- format_val(risultati_comb_std_df$mean[i], p_name)
  risultati_finali_print$percentile_2.5[i] <- format_val(risultati_comb_std_df$percentile_2.5[i], p_name)
  risultati_finali_print$percentile_97.5[i] <- format_val(risultati_comb_std_df$percentile_97.5[i], p_name)
}

# --- 6. Stampa finale ---
print(risultati_finali_print)

```

```{r FP, echo=FALSE}
library(tidyverse)
library(metafor)
library(bayesplot)
library(dplyr)
library(ggplot2)
library(HDInterval)
# 1. Filtra solo i parametri 'd' (componenti principali) dal dataframe dei risultati
component_results <- risultati_comb_std_df %>%
  tibble::rownames_to_column("parameter") %>%
  filter(grepl("^d\\[", parameter)) %>%
  # Escludi d[1] se presente
  filter(parameter != "d[1]")

# 2. Aggiungi i nomi delle componenti (assicurati che l'ordine corrisponda)
component_results$component <- components[-1] # Escludi la prima componente

# 3. Ordina per stima puntuale (opzionale)
component_results <- component_results %>%
  arrange(median)

# 4. Crea il forest plot
forest_plot_from_results <- ggplot(component_results, 
       aes(y = factor(component, levels = rev(component)), 
           x = median, 
           xmin = percentile_2.5, 
           xmax = percentile_97.5)) +
  geom_point(size = 3) +
  geom_errorbar(width = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  scale_x_continuous(breaks = seq(-1, +1, by = 0.2),  # Sequence from -1 to +1 by 0.2
                     limits = c(-1.2, +1.2)) +          # Set axis limits
  xlab("Effect Estimate (outcome on the 0-100 scale)") +
  ylab("Component") +
  ggtitle("Forest Plot of Component Effects") +
  theme_bw()

print(forest_plot_from_results)
```

```{r exclude d1, include=FALSE}
library(coda)

samples_for_diag <- lapply(samps_lambda_std_no_IF_interaz, function(imp) {
  
  # imp è una lista di catene per UNA imputazione
  
  filtered_chains <- lapply(imp, function(chain) {
    
    param_names <- colnames(chain)
    
    params_to_keep <- 
      !grepl("^d\\[1\\]$", param_names) &
      !grepl("^gamma\\..*\\[9\\]$", param_names)
    
    chain[, params_to_keep, drop = FALSE]
  })
  
  as.mcmc.list(filtered_chains)
})

```

```{r psrf_mat, include=FALSE}
# 1) Calcola il Gelman–Rubin per ogni imputazione
psrf_by_imp <- lapply(samples_for_diag, function(mcmc_imp) {
  gelman.diag(mcmc_imp)
})

# 2) Estrai i PSRF (Point estimate) per ciascun parametro e imputazione
psrf_list <- lapply(psrf_by_imp, function(res) {
  res$psrf[, "Point est."]
})

# 3) Costruisci la matrice:
#    righe = parametri, colonne = imputazioni
psrf_mat <- do.call(cbind, psrf_list)

colnames(psrf_mat) <- paste0("imp", seq_along(psrf_list))
rownames(psrf_mat) <- rownames(psrf_by_imp[[1]]$psrf)
```

```{r psrf, include=FALSE}
psrf_summary_across_imp <- data.frame(
  mean_psrf = formatC(
    rowMeans(psrf_mat, na.rm = TRUE),
    format = "f", digits = 2
  ),
  median_psrf = formatC(
    apply(psrf_mat, 1, median, na.rm = TRUE),
    format = "f", digits = 2
  )
)

psrf_summary_across_imp

```




```{r mpsrf, include=FALSE}
# Estrai la Multivariate PSRF per ogni imputazione
mpsrf_vec <- sapply(psrf_by_imp, function(res) res$mpsrf)

# Media e mediana ACROSS imputations
mpsrf_summary_across_imp <- data.frame(
  mean_mpsrf = formatC(mean(mpsrf_vec, na.rm = TRUE),
                       format = "f", digits = 2),
  median_mpsrf = formatC(median(mpsrf_vec, na.rm = TRUE),
                         format = "f", digits = 2)
)

mpsrf_summary_across_imp
```

```{r ess_centered, echo=FALSE}
library (coda)


center_imputation <- function(mcmc_list) {
  mat <- as.matrix(mcmc_list)     # draws concatenati
  mu  <- colMeans(mat)            # media per parametro
  
  centered <- lapply(mcmc_list, function(chain) {
    sweep(chain, 2, mu, "-")
  })
  
  as.mcmc.list(centered)
}

centered_by_imp <- lapply(samples_for_diag, center_imputation)

centered_10chains <- as.mcmc.list(
  unlist(centered_by_imp, recursive = FALSE)
)
ess_centered <- effectiveSize(centered_10chains)
summary(ess_centered)

n_iter <- niter(centered_10chains[[1]])
ess_ratio <- ess_centered / (10 * n_iter)
```

```{r psrf_centered, echo=FALSE}
psrf_centered <- gelman.diag(
  centered_10chains,
  multivariate = FALSE
)
psrf_centered_summary <- data.frame(
  mean_psrf = formatC(
    mean(psrf_centered$psrf[, "Point est."], na.rm = TRUE),
    format = "f", digits = 2
  ),
  median_psrf = formatC(
    median(psrf_centered$psrf[, "Point est."], na.rm = TRUE),
    format = "f", digits = 2
  ),
  max_upper = formatC(
    max(psrf_centered$psrf[, "Upper C.I."], na.rm = TRUE),
    format = "f", digits = 2
  )
)

psrf_centered_summary

psrf_by_param <- data.frame(
  parameter = rownames(psrf_centered$psrf),
  psrf_point = formatC(
    psrf_centered$psrf[, "Point est."],
    format = "f", digits = 2
  ),
  psrf_upper = formatC(
    psrf_centered$psrf[, "Upper C.I."],
    format = "f", digits = 2
  ),
  row.names = NULL
)

psrf_by_param


```

```{r descaling, echo=FALSE}
# 1. Calcolo SD (Età fissa, altre da merged_imp)
sd_age    <- sd(as.numeric(merged_imp$age), na.rm = TRUE)
sd_gender <- sd(as.numeric(merged_imp$gender), na.rm = TRUE)
sd_empl   <- sd(as.numeric(merged_imp$empl_bin), na.rm = TRUE)
sd_stc    <- sd(as.numeric(merged_imp$stc_bin), na.rm = TRUE)
sd_edu    <- sd(as.numeric(merged_imp$edu_bin), na.rm = TRUE)

sd_map <- c(
  "beta.age"      = sd_age,
  "beta.gender"   = sd_gender,
  "beta.empl_bin" = sd_empl,
  "beta.stc_bin"  = sd_stc,
  "beta.edu_bin"  = sd_edu,
  "beta.baseline" = 1
)
# 1. Usiamo la matrice all_chains_std_lambda che hai appena creato con successo
# (Assicurati di aver eseguito il tuo blocco di codice precedente prima di questo)

risultati_finali_list <- list()

# Prendiamo tutti i nomi dei parametri presenti (beta, d, gamma, etc.)
tutti_i_nomi <- colnames(all_chains_std_lambda)

for (parametro in tabetutti_i_nomi) {
    
    # Estraiamo i campioni grezzi
    campioni_raw <- all_chains_std_lambda[, parametro]
    
    # 2. Logica De-scaling
    # Applichiamo il divider dal tuo sd_map se il parametro è una delle beta covariate
    divider <- 1
    if (exists("sd_map") && parametro %in% names(sd_map)) {
        divider <- sd_map[parametro]
    }
    
    # Calcolo dei valori de-standardizzati
    # Nota: per d[1], se i dati originali sono 0, rimarranno 0
    campioni_unstd <- campioni_raw / divider
    
    # 3. Calcolo statistiche e formattazione
    m_val    <- median(campioni_unstd)
    mean_val <- mean(campioni_unstd)
    q_low    <- as.numeric(quantile(campioni_unstd, 0.025))
    q_high   <- as.numeric(quantile(campioni_unstd, 0.975))
    
    # Creazione della riga formattata
    risultati_finali_list[[parametro]] <- data.frame(
        Parameter       = parametro,
        Median          = sprintf("%.4f", m_val),
        Mean            = sprintf("%.4f", mean_val),
        Percentile_2.5  = sprintf("%.4f", q_low),
        Percentile_97.5 = sprintf("%.4f", q_high),
        stringsAsFactors = FALSE
    )
}

# 4. Unione e Filtro per il Paper
risultati_unstd_df <- do.call(rbind, risultati_finali_list)

# Filtriamo per mostrare solo quello che serve: beta, d e gamma
tabella_paper <- risultati_unstd_df[grepl("beta|d\\[|gamma", risultati_unstd_df$Parameter), ]

# Ordiniamo alfabeticamente per avere beta, poi d, poi gamma
tabella_paper <- tabella_paper[order(tabella_paper$Parameter), ]

# 5. Visualizzazione finale
print(knitr::kable(tabella_paper, row.names = FALSE, caption = "Tabella Risultati Definitiva (Unstandardized)"))
```

```{r unscaled, include=FALSE}
# 1. SD Map (basata sul tuo dataset originale merged_imp)
sd_map <- c(
  "beta.age"      = sd(as.numeric(merged_imp$age), na.rm = TRUE),
  "beta.gender"   = sd(as.numeric(merged_imp$gender), na.rm = TRUE),
  "beta.empl_bin" = sd(as.numeric(merged_imp$empl_bin), na.rm = TRUE),
  "beta.stc_bin"  = sd(as.numeric(merged_imp$stc_bin), na.rm = TRUE),
  "beta.edu_bin"  = sd(as.numeric(merged_imp$edu_bin), na.rm = TRUE),
  "beta.baseline" = 1 
)

# 2. Creazione Tabella usando la matrice 'all_chains_std_lambda' (quella del tuo log)
risultati_finali_list <- list()

# Recuperiamo i nomi dei parametri
nomi_parametri <- colnames(all_chains_std_lambda)

for (p in nomi_parametri) {
    # Estraiamo i campioni dalla matrice che sappiamo esistere
    campioni <- all_chains_std_lambda[, p]
    
    # De-scaling: dividiamo per la SD se il parametro è una delle beta covariate
    divider <- if (p %in% names(sd_map)) sd_map[p] else 1
    campioni_unstd <- campioni / divider
    
    # Calcolo statistiche
    risultati_finali_list[[p]] <- data.frame(
        Parameter       = p,
        Median          = sprintf("%.4f", median(campioni_unstd)),
        Mean            = sprintf("%.4f", mean(campioni_unstd)),
        CI_2.5          = sprintf("%.4f", as.numeric(quantile(campioni_unstd, 0.025))),
        CI_97.5         = sprintf("%.4f", as.numeric(quantile(campioni_unstd, 0.975))),
        stringsAsFactors = FALSE
    )
}

# 3. Unione e Filtro per il paper
tabella_completa <- do.call(rbind, risultati_finali_list)
tabella_final <- tabella_completa[grepl("beta|d\\[|gamma", tabella_completa$Parameter), ]

# Visualizzazione finale
print(knitr::kable(tabella_final, row.names = FALSE, align = "lcccc"))
```

```{r interaz, include=FALSE}
#  Recupera i nomi direttamente dalla matrice risultante
nomi_p <- colnames(all_chains_std_lambda)

# VERIFICA: Deve darti un numero tipo 66 o simile
cat("Numero di parametri trovati:", length(nomi_p), "\n")
risultati_finali_list <- list()

for (p in nomi_p) {
    campioni <- all_chains_std_lambda[, p]
    
    # De-scaling usando la tua sd_map
    divider <- if (exists("sd_map") && p %in% names(sd_map)) sd_map[p] else 1
    campioni_unstd <- campioni / divider
    
    # Calcolo statistiche con protezione per NA
    risultati_finali_list[[p]] <- data.frame(
        Parameter       = p,
        Median          = sprintf("%.4f", median(campioni_unstd, na.rm = TRUE)),
        Mean            = sprintf("%.4f", mean(campioni_unstd, na.rm = TRUE)),
        CI_2.5          = sprintf("%.4f", as.numeric(quantile(campioni_unstd, 0.025, na.rm = TRUE))),
        CI_97.5         = sprintf("%.4f", as.numeric(quantile(campioni_unstd, 0.975, na.rm = TRUE))),
        stringsAsFactors = FALSE
    )
}

# 3. Unione e Filtro
tabella_completa <- do.call(rbind, risultati_finali_list)
tabella_final <- tabella_completa[grepl("beta|d\\[|gamma", tabella_completa$Parameter), ]

# Visualizzazione finale
print(knitr::kable(tabella_final, row.names = FALSE, align = "lcccc"))
```

```{r maxitab, echo=FALSE}
# --- COSTRUZIONE LISTE CORRETTA ---
tab_1_list <- list() 
tab_2_list <- list() 

# 1. SD per Covariate (usate per de-standardizzare in Tab 1)
sd_map_covs <- c(
  "age"      = sd(merged_imp$age, na.rm = TRUE), 
  "gender"   = sd(as.numeric(as.character(merged_imp$gender)), na.rm = TRUE), 
  "empl_bin" = sd(as.numeric(merged_imp$empl_bin), na.rm = TRUE), 
  "stc_bin"  = sd(as.numeric(merged_imp$stc_bin), na.rm = TRUE), 
  "edu_bin"  = sd(as.numeric(merged_imp$edu_bin), na.rm = TRUE)
)

# 2. SD per Componenti e Baseline (usate per standardizzare in Tab 2)
sd_map_comps <- c(
  "d[2]" = sd(as.numeric(dataIPD$PE), na.rm = TRUE),
  "d[3]" = sd(as.numeric(dataIPD$CR), na.rm = TRUE),
  "d[4]" = sd(as.numeric(dataIPD$ACC), na.rm = TRUE),
  "d[5]" = sd(as.numeric(dataIPD$REL), na.rm = TRUE),
  "d[6]" = sd(as.numeric(dataIPD$PM), na.rm = TRUE),
  "d[7]" = sd(as.numeric(dataIPD$BA), na.rm = TRUE),
  "d[8]" = sd(as.numeric(dataIPD$SSS), na.rm = TRUE),
  "d[9]" = sd(as.numeric(dataIPD$IF), na.rm = TRUE)
)
sd_baseline_orig <- sd(merged_imp$baseline, na.rm = TRUE)

nomi_p_fissi <- c("beta.baseline", paste0("d[", 2:9, "]"))
all_params <- colnames(all_chains_std_lambda)
# Correzione filtro: usiamo 'all_params' e non la variabile di loop 'p'
params_std_in_model <- all_params[grepl("beta|gamma", all_params) & all_params != "beta.baseline"]

# A. LOOP PARAMETRI FISSI (Non standardizzati nel modello JAGS)
for(p in nomi_p_fissi) {
  if(p %in% all_params) {
    # Tabella 1: Scala clinica (SMD per unità di punto/trattamento)
    tab_1_list[[p]] <- all_chains_std_lambda[, p]
    
    # Tabella 2: Z-score (Standardizzo X moltiplicando per la sua SD)
    if(p == "beta.baseline") {
      tab_2_list[[p]] <- all_chains_std_lambda[, p] * sd_baseline_orig
    } else {
      tab_2_list[[p]] <- all_chains_std_lambda[, p] * sd_map_comps[p]
    }
  }
}

# B. LOOP COVARIATE E INTERAZIONI (Già standardizzate nel modello JAGS)
for(p in params_std_in_model) {
  # Tabella 2: Restano Z-score (già scalati rispetto a X nel modello)
  tab_2_list[[p]] <- all_chains_std_lambda[, p]
  
  # Tabella 1: De-standardizzazione rispetto a X (Torno all'unità naturale)
  divisor <- 1
  for(root in names(sd_map_covs)) {
    if(grepl(root, p)) {
      divisor <- sd_map_covs[root] # <--- CORRETTO: usa sd_map_covs, non sd_map_comps!
      break
    }
  }
  tab_1_list[[p]] <- all_chains_std_lambda[, p] / divisor
}

# 1. DEFINIAMO LA FUNZIONE (Il "traduttore")
summarize_final <- function(samples) {
  samples <- samples[!is.na(samples)]
  if(length(samples) == 0) return("N/A")
  
  mn   <- mean(samples)
  med  <- median(samples)
  low  <- quantile(samples, 0.025)
  high <- quantile(samples, 0.975)
  
  # Questo crea il formato: Mediana (Media) [95% Intervallo]
  sprintf("%.4f (%.4f) [%.4f, %.4f]", med, mn, low, high)
}

# Crea la Tabella 1
tabella_1_unstd <- data.frame(
  Parameter = names(tab_1_list), 
  `Median (Mean) [95% CrI]` = sapply(tab_1_list, summarize_final),
  check.names = FALSE
)

# Crea la Tabella 2
tabella_2_std <- data.frame(
  Parameter = names(tab_2_list), 
  `Median (Mean) [95% CrI]` = sapply(tab_2_list, summarize_final),
  check.names = FALSE
)
```
