---
title: "Analysis_per_trialname_normal_FT"
author: "Federico Tedeschi"
date: "2025-06-25"
output: word_document
---
  RE_SHIFT_2025aprile13
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
rm(list=ls())

### load data

library(tidyverse)
library(readxl)
load("C://Users//tdsfrc40//OneDrive - Università degli Studi di Verona//Z//Federico_main//Lavori_Vr//ongoing//lavori_gruppo_CB//NMA//IPD_NMA_RESHIFT//aggiornamenti_RE_SHIFT//dataset_to_impute_DO.RData")
full_dataset <- full_dataset %>% mutate(age = if_else(trialname == "Rahman 2019" & age==3, NA, age))
```



```{r, include=FALSE, message=FALSE, warning=FALSE}
if (!require("remotes")) install.packages("remotes")
remotes::install_github("blimp-stats/rblimp")
library(rblimp)
```


```{r, include=FALSE, message=FALSE, warning=FALSE}
colnames(full_dataset)
education<-full_dataset$education 
marital<-full_dataset$marital
occupation<-full_dataset$occupation 
trialname<-full_dataset$trialname 
cluster<-full_dataset$cluster
participantId<-full_dataset$participantId
arm<-full_dataset$arm 
gender<-full_dataset$gender
age<-full_dataset$age
dropout<-full_dataset$dropout
#endpoint<-full_dataset$endpoint_CMD_pct
baseline<-full_dataset$baseline_CMD_pct
TAU<-full_dataset$TAU
PE<-full_dataset$PE
CR<-full_dataset$CR
ACC<-full_dataset$ACC
REL<-full_dataset$REL
PM<-full_dataset$PM 
BA<-full_dataset$BA
SSS<-full_dataset$SSS

IF<-full_dataset$IF


# Let's see what is missing

summary(as.numeric(education))
summary(as.numeric(marital))
summary(as.numeric(occupation))
summary(as.numeric(gender))
summary(as.numeric(age))
#summary(as.numeric(endpoint))
summary(as.numeric(baseline))
summary(as.numeric(dropout))
# they all have missing values, apart from dropout
```

```{r transformation, include=FALSE, message=FALSE, warning=FALSE}
full_dataset$stc_bin <- ifelse(is.na(full_dataset$marital), NA,
                                ifelse(full_dataset$marital %in% c("1"), "1", "0"))

full_dataset$empl_bin <- ifelse(is.na(full_dataset$occupation), NA,
                                ifelse(full_dataset$occupation %in% c("1"), "1", "0"))
full_dataset$edu_bin <- ifelse(full_dataset$education %in% c("0", "1"), "0", "1")
full_dataset$age <- as.numeric(full_dataset$age)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
baseline_mean<-mean(as.numeric(baseline), na.rm=T)
sprintf("%.16f", baseline_mean)
baseline_sd<-sd(as.numeric(baseline), na.rm=T)
sprintf("%.16f", baseline_sd)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
# Prepara i dati (converti fattori e assicurati che i cluster siano univoci)
full_dataset$cluster[is.na(full_dataset$cluster)]<- 1
full_dataset <- full_dataset %>%
  mutate(
    across(c(gender, edu_bin, stc_bin, empl_bin, dropout), as.factor),
    cluster_unique = as.numeric(interaction(trialname, cluster))  # Cluster univoci
  )



# Definisci l'ordine delle colonne desiderato
#full_dataset$age_scaled <- scale(full_dataset$age)

# Scalatura Z-score per 'baseline'
#full_dataset$baseline<- scale(full_dataset$baseline_CMD_pct)
full_dataset$y<- full_dataset$dropout
#full_dataset$cluster<- full_dataset$cluster_unique
full_dataset$particId<-as.numeric(as.factor(full_dataset$participantId))
#age_scaled<-full_dataset$age_scaled
#baseline_scaled<-full_dataset$baseline_scaled
#drop <- c("baseline_CMD_pctg","endpoint_CMD_standardizzato")
#full_dataset = full_dataset[,!(names(full_dataset) %in% drop)]

desired_order <- c("particId", "age", "baseline",
                   "y", "TAU", "PE", "CR", "ACC", "REL", "PM", "BA", "SSS", "IF", "gender", "edu_bin", "stc_bin", "empl_bin", "trialname", "cluster_unique")



full_dataset_per_imp <- full_dataset %>% 
  select(all_of(desired_order))

full_dataset_per_imp$trialnum<-as.numeric(as.factor(full_dataset_per_imp$trialname))
#full_dataset_per_imp$particId<-as.numeric(as.factor(full_dataset_per_imp$particId))
full_dataset_per_imp$baseline<-full_dataset$baseline_CMD_pct
#full_dataset_per_imp$edu_bin<-as.factor(full_dataset_per_imp$edu_bin)
names(full_dataset_per_imp)

#full_dataset_per_imp <- full_dataset_per_imp %>%
 # group_by(trialname) %>% # Raggruppa i dati per trialname
  #mutate(cluster_unique_reindexed = dense_rank(cluster_unique)) %>% # Crea un nuovo ID numerico che riparte da 1 per ogni gruppo
  #ungroup() # Rimuovi il raggruppamento

# Seleziona e riordina le colonne
#full_dataset_per_imp <- full_dataset[, desired_order]
#full_dataset_per_imp$participantId<-as.numeric(full_dataset_per_imp$participantId)
full_dataset_per_imp <- full_dataset_per_imp %>%
select(-trialname)  
#write.csv(full_dataset_per_imp, "full_dataset_per_imp.csv", row.names = FALSE, na = "NA", quote = FALSE)
write.table(full_dataset_per_imp, "full_dataset_per_imp_DO.csv", sep = "," , dec = ".", row.names = FALSE, col.names = FALSE, na = "NA", quote = FALSE)
```


```{r model, include=FALSE, message=FALSE, warning=FALSE}
model <- "
DATA: full_dataset_per_imp_DO.csv;

VARIABLES: 
  particId age baseline y
  TAU PE CR ACC REL PM BA SSS IF
  gender edu_bin stc_bin empl_bin
   cluster_unique trialnum;

CLUSTERID: trialnum cluster_unique;

NOMINAL: y gender empl_bin stc_bin  edu_bin PE CR ACC REL PM BA SSS IF;
MISSING: NA;

MODEL:
  # -------------------------
  # OUTCOME (modello finale)
  # -------------------------
  
  # -------------------------
  # IMPUTAZIONE PREDITTORI CON MISSING
  # -------------------------

  age ~ baseline gender edu_bin empl_bin stc_bin
        PE CR ACC REL PM BA SSS IF
        baseline*PE gender*PE edu_bin*PE empl_bin*PE stc_bin*PE
        baseline*CR gender*CR edu_bin*CR empl_bin*CR stc_bin*CR
        baseline*ACC gender*ACC edu_bin*ACC empl_bin*ACC stc_bin*ACC
        baseline*REL gender*REL edu_bin*REL empl_bin*REL stc_bin*REL
        baseline*PM  gender*PM  edu_bin*PM  empl_bin*PM  stc_bin*PM
        baseline*BA  gender*BA  edu_bin*BA  empl_bin*BA  stc_bin*BA
        baseline*SSS gender*SSS edu_bin*SSS empl_bin*SSS stc_bin*SSS
        baseline*IF  gender*IF  edu_bin*IF  empl_bin*IF  stc_bin*IF
        y | 1[trialnum] ;

  baseline ~ age gender edu_bin empl_bin stc_bin
             PE CR ACC REL PM BA SSS IF
             gender*PE edu_bin*PE empl_bin*PE stc_bin*PE
             gender*CR edu_bin*CR empl_bin*CR stc_bin*CR
             gender*ACC edu_bin*ACC empl_bin*ACC stc_bin*ACC
             gender*REL edu_bin*REL empl_bin*REL stc_bin*REL
             gender*PM  edu_bin*PM  empl_bin*PM  stc_bin*PM
             gender*BA  edu_bin*BA  empl_bin*BA  stc_bin*BA
             gender*SSS edu_bin*SSS empl_bin*SSS stc_bin*SSS
             gender*IF  edu_bin*IF  empl_bin*IF  stc_bin*IF
             y | 1[trialnum] 1[cluster_unique] ;

gender ~ age baseline edu_bin empl_bin stc_bin
             PE CR ACC REL PM BA SSS IF
             baseline*PE edu_bin*PE empl_bin*PE stc_bin*PE
             baseline*CR edu_bin*CR empl_bin*CR stc_bin*CR
             baseline*ACC edu_bin*ACC empl_bin*ACC stc_bin*ACC
             baseline*REL edu_bin*REL empl_bin*REL stc_bin*REL
             baseline*PM  edu_bin*PM  empl_bin*PM  stc_bin*PM
             baseline*BA  edu_bin*BA  empl_bin*BA  stc_bin*BA
             baseline*SSS edu_bin*SSS empl_bin*SSS stc_bin*SSS
             baseline*IF  edu_bin*IF  empl_bin*IF  stc_bin*IF
             y | 1[trialnum] ;


  edu_bin ~ age baseline gender empl_bin stc_bin
            PE CR ACC REL PM BA SSS IF
            age*PE baseline*PE gender*PE empl_bin*PE stc_bin*PE
            age*CR baseline*CR gender*CR empl_bin*CR stc_bin*CR
            age*ACC baseline*ACC gender*ACC empl_bin*ACC stc_bin*ACC
            age*REL baseline*REL gender*REL empl_bin*REL stc_bin*REL
            age*PM  baseline*PM  gender*PM  empl_bin*PM  stc_bin*PM
            age*BA  baseline*BA  gender*BA  empl_bin*BA  stc_bin*BA
            age*SSS baseline*SSS gender*SSS empl_bin*SSS stc_bin*SSS
            age*IF  baseline*IF  gender*IF  empl_bin*IF  stc_bin*IF
            y | 1[trialnum] ;

  empl_bin ~ age baseline gender edu_bin stc_bin
             PE CR ACC REL PM BA SSS IF
             age*PE baseline*PE gender*PE edu_bin*PE stc_bin*PE
             age*CR baseline*CR gender*CR edu_bin*CR stc_bin*CR
             age*ACC baseline*ACC gender*ACC edu_bin*ACC stc_bin*ACC
             age*REL baseline*REL gender*REL edu_bin*REL stc_bin*REL
             age*PM  baseline*PM  gender*PM  edu_bin*PM  stc_bin*PM
             age*BA  baseline*BA  gender*BA  edu_bin*BA  stc_bin*BA
             age*SSS baseline*SSS gender*SSS edu_bin*SSS stc_bin*SSS
             age*IF  baseline*IF  gender*IF  edu_bin*IF  stc_bin*IF
             y | 1[trialnum] ;

  stc_bin ~ age baseline gender edu_bin empl_bin
             PE CR ACC REL PM BA SSS IF
             age*PE baseline*PE gender*PE edu_bin*PE empl_bin*PE
             age*CR baseline*CR gender*CR edu_bin*CR empl_bin*CR
             age*ACC baseline*ACC gender*ACC edu_bin*ACC empl_bin*ACC
             age*REL baseline*REL gender*REL edu_bin*REL empl_bin*REL
             age*PM  baseline*PM  gender*PM  edu_bin*PM  empl_bin*PM
             age*BA  baseline*BA  gender*BA  edu_bin*BA  empl_bin*BA
             age*SSS baseline*SSS gender*SSS edu_bin*SSS empl_bin*SSS
             age*IF  baseline*IF  gender*IF  edu_bin*IF empl_bin*IF
             y | 1[trialnum] ;

SEED: 126;
NIMPS: 5;
BURN: 5000; 
ITER: 10000; 
OPTIONS: labels;
OUTFILE: imputed_blimp_DO_full*.csv;
"


# Salvataggio del modello in un file
writeLines(model, "blimp_model_DO_full.txt")
```


```{r, include=FALSE, message=FALSE, warning=FALSE}
system("blimp blimp_model_DO_full.txt")
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
save.image(file="C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\aggiornamenti_RE_SHIFT\\full_dataset_imputed_DO_PE_interaz.RData")
```

```{r, include=FALSE}
rm(list=ls())
setwd("C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\aggiornamenti_RE_SHIFT")
load(file="full_dataset_imputed_DO_PE_interaz.RData")
#full_dataset<-full_dataset
library(tidyverse)


setwd("C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\an_binary_outcome")
# 1. Trova tutti i file imputati
imputed_files <- list.files(pattern = "imputed_blimp_DO_full\\d+\\.csv")

# 2. Carica i file aggiungendo una colonna con il numero di imputazione
imputed_list <- map(imputed_files, function(file) {
  read_csv(file, col_names = FALSE, show_col_types = FALSE) %>% 
    mutate(imputation = str_extract(file, "\\d+"))
})

# 3. Assegna i nomi corretti alle colonne (ADATTALI AL TUO full_dataset!)
col_names <- c("particId", "age", "baseline", "dropout", 
               "TAU", "PE", "CR", "ACC", "REL", "PM", "BA", "SSS", "IF",
               "gender", "edu_bin", "stc_bin", "empl_bin", "cluster_unique",
               "trialnum",  "imputation")

# 4. Applica i nomi delle colonne a ciascun dataframe
imputed_list <- map(imputed_list, ~set_names(.x, col_names))





# 5. Combina in un unico dataframe
imputed_data <- bind_rows(imputed_list) %>% 
  mutate(across(c(gender, edu_bin, stc_bin, empl_bin, dropout), as.factor))

# Verifica
glimpse(imputed_data)
summary(imputed_data$dropout)
# la presenza di valori "out of range" (-61, 125) aumenta la necessità di togliere i valori imputati  
```

```{r, echo=FALSE}
# Salva il risultato
write_csv(imputed_data, "full_dataset_DO_all_interaz.csv")
```

```{r, echo=FALSE}
class(imputed_data)
```

with such variables:

```{r, echo=FALSE}
names(imputed_data)
```

, corresponding to such dimensions:

```{r, echo=FALSE}
dim(imputed_data)
```

These are the original (partially observed) data:

```{r, echo=FALSE}
head(imputed_data)
```

This the (partially observed) last imputation:

```{r, echo=FALSE}
head(imputed_data[imputed_data$imputation == 5,])
#save(imputed_data, file="C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\aggiornamenti_RE_SHIFT\\full_dataset_imputed_26_03_25_with_comp.RData")
#write.xlsx(imputed_data, file = "C:/Users/tdsfrc40/OneDrive - Università degli Studi di Verona/Z/Federico_main/Lavori_Vr/ongoing/lavori_gruppo_CB/NMA/IPD_NMA_RESHIFT/full_dataset_imp_04_06_25.xlsx",sheetName = "full_dataset_imp_with_comp", append = FALSE)
save.image(file="C:\\Users\\tdsfrc40\\OneDrive - Università degli Studi di Verona\\Z\\Federico_main\\Lavori_Vr\\ongoing\\lavori_gruppo_CB\\NMA\\IPD_NMA_RESHIFT\\aggiornamenti_RE_SHIFT\\full_dataset_DO_with_all_interaz.RData")
```

